# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActivateFarmElementScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x41\x63tivateFarmElementScRsp.proto\"S\n\x18\x41\x63tivateFarmElementScRsp\x12\x13\n\x0bworld_level\x18\x0b \x01(\r\x12\x11\n\tentity_id\x18\x0c \x01(\r\x12\x0f\n\x07retcode\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ActivateFarmElementScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACTIVATEFARMELEMENTSCRSP']._serialized_start=34
  _globals['_ACTIVATEFARMELEMENTSCRSP']._serialized_end=117
# @@protoc_insertion_point(module_scope)
