# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddRogueMiracleScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueMiracleSource_pb2 as RogueMiracleSource__pb2
import RogueMiracle_pb2 as RogueMiracle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x41\x64\x64RogueMiracleScNotify.proto\x1a\x18RogueMiracleSource.proto\x1a\x12RogueMiracle.proto\"d\n\x17\x41\x64\x64RogueMiracleScNotify\x12#\n\x06source\x18\x0f \x01(\x0e\x32\x13.RogueMiracleSource\x12$\n\rrogue_miracle\x18\x04 \x01(\x0b\x32\r.RogueMiracleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AddRogueMiracleScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDROGUEMIRACLESCNOTIFY']._serialized_start=79
  _globals['_ADDROGUEMIRACLESCNOTIFY']._serialized_end=179
# @@protoc_insertion_point(module_scope)
