# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddRogueBuffScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuff_pb2 as RogueBuff__pb2
import RogueBuffSource_pb2 as RogueBuffSource__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x41\x64\x64RogueBuffScNotify.proto\x1a\x0fRogueBuff.proto\x1a\x15RogueBuffSource.proto\"\\\n\x14\x41\x64\x64RogueBuffScNotify\x12 \n\x06source\x18\x04 \x01(\x0e\x32\x10.RogueBuffSource\x12\"\n\x0emaze_buff_info\x18\x01 \x01(\x0b\x32\n.RogueBuffb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AddRogueBuffScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDROGUEBUFFSCNOTIFY']._serialized_start=70
  _globals['_ADDROGUEBUFFSCNOTIFY']._serialized_end=162
# @@protoc_insertion_point(module_scope)
