# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AssistSimpleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x41ssistSimpleInfo.proto\"Z\n\x10\x41ssistSimpleInfo\x12\x11\n\tavatar_id\x18\x03 \x01(\r\x12\x0b\n\x03pos\x18\x06 \x01(\r\x12\r\n\x05level\x18\x01 \x01(\r\x12\x17\n\x0f\x64ressed_skin_id\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AssistSimpleInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ASSISTSIMPLEINFO']._serialized_start=26
  _globals['_ASSISTSIMPLEINFO']._serialized_end=116
# @@protoc_insertion_point(module_scope)
