# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarType.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x41vatarType.proto*\x80\x01\n\nAvatarType\x12\x14\n\x10\x41VATAR_TYPE_NONE\x10\x00\x12\x15\n\x11\x41VATAR_TRIAL_TYPE\x10\x01\x12\x15\n\x11\x41VATAR_LIMIT_TYPE\x10\x02\x12\x16\n\x12\x41VATAR_FORMAL_TYPE\x10\x03\x12\x16\n\x12\x41VATAR_ASSIST_TYPE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AVATARTYPE']._serialized_start=21
  _globals['_AVATARTYPE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
