# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarProperty.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41vatarProperty.proto\"\x82\x01\n\x0e\x41vatarProperty\x12\x0e\n\x06max_hp\x18\x01 \x01(\x01\x12\x0e\n\x06\x61ttack\x18\x02 \x01(\x01\x12\x0f\n\x07\x64\x65\x66\x65nce\x18\x03 \x01(\x01\x12\r\n\x05speed\x18\x04 \x01(\x01\x12\x0f\n\x07left_hp\x18\x05 \x01(\x01\x12\x0f\n\x07left_sp\x18\x06 \x01(\x01\x12\x0e\n\x06max_sp\x18\x07 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarProperty_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AVATARPROPERTY']._serialized_start=25
  _globals['_AVATARPROPERTY']._serialized_end=155
# @@protoc_insertion_point(module_scope)
