# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Avatar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarSkillTree_pb2 as AvatarSkillTree__pb2
import EquipRelic_pb2 as EquipRelic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x41vatar.proto\x1a\x15\x41vatarSkillTree.proto\x1a\x10\x45quipRelic.proto\"\xab\x02\n\x06\x41vatar\x12\x11\n\tpromotion\x18\r \x01(\r\x12\x1b\n\x13\x65quipment_unique_id\x18\x05 \x01(\r\x12\x1b\n\x13\x66irst_met_timestamp\x18\x0e \x01(\x04\x12\x17\n\x0f\x64ressed_skin_id\x18\x0f \x01(\r\x12\x11\n\tis_marked\x18\x02 \x01(\x08\x12\x16\n\x0e\x62\x61se_avatar_id\x18\x01 \x01(\r\x12(\n\x0eskilltree_list\x18\x0c \x03(\x0b\x32\x10.AvatarSkillTree\x12\x0c\n\x04rank\x18\x0b \x01(\r\x12%\n\x10\x65quip_relic_list\x18\x07 \x03(\x0b\x32\x0b.EquipRelic\x12\x15\n\rtaken_rewards\x18\x06 \x03(\r\x12\x0b\n\x03\x65xp\x18\n \x01(\r\x12\r\n\x05level\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Avatar_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AVATAR']._serialized_start=58
  _globals['_AVATAR']._serialized_end=357
# @@protoc_insertion_point(module_scope)
