# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AvatarBattleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarProperty_pb2 as AvatarProperty__pb2
import AvatarType_pb2 as AvatarType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x41vatarBattleInfo.proto\x1a\x14\x41vatarProperty.proto\x1a\x10\x41vatarType.proto\"\xad\x01\n\x10\x41vatarBattleInfo\x12 \n\x0b\x61vatar_type\x18\x01 \x01(\x0e\x32\x0b.AvatarType\x12\n\n\x02id\x18\x02 \x01(\r\x12\x14\n\x0c\x61vatar_level\x18\x03 \x01(\r\x12\x13\n\x0b\x61vatar_rank\x18\x04 \x01(\r\x12\x18\n\x10\x61vatar_promotion\x18\x05 \x01(\r\x12&\n\ravatar_status\x18\x06 \x01(\x0b\x32\x0f.AvatarPropertyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AvatarBattleInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AVATARBATTLEINFO']._serialized_start=67
  _globals['_AVATARBATTLEINFO']._serialized_end=240
# @@protoc_insertion_point(module_scope)
