# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleStatistics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarBattleInfo_pb2 as AvatarBattleInfo__pb2
import BattleEndReason_pb2 as BattleEndReason__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x42\x61ttleStatistics.proto\x1a\x16\x41vatarBattleInfo.proto\x1a\x15\x42\x61ttleEndReason.proto\"\xeb\x03\n\x10\x42\x61ttleStatistics\x12\x1a\n\x12total_battle_turns\x18\x01 \x01(\r\x12\x18\n\x10total_auto_turns\x18\x02 \x01(\r\x12\x16\n\x0e\x61vatar_id_list\x18\x03 \x03(\r\x12\x11\n\tultra_cnt\x18\x04 \x01(\r\x12\x1c\n\x14total_delay_cumulate\x18\x05 \x01(\x01\x12\x11\n\tcost_time\x18\x06 \x01(\x01\x12-\n\x12\x62\x61ttle_avatar_list\x18\x07 \x03(\x0b\x32\x11.AvatarBattleInfo\x12\x11\n\tround_cnt\x18\t \x01(\r\x12\x18\n\x10\x63ocoon_dead_wave\x18\n \x01(\r\x12\x1b\n\x13\x61vatar_battle_turns\x18\x0b \x01(\r\x12\x1c\n\x14monster_battle_turns\x18\x0c \x01(\r\x12:\n\rcustom_values\x18\r \x03(\x0b\x32#.BattleStatistics.CustomValuesEntry\x12\x17\n\x0f\x63hallenge_score\x18\x0e \x01(\r\x12$\n\nend_reason\x18\x13 \x01(\x0e\x32\x10.BattleEndReason\x1a\x33\n\x11\x43ustomValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattleStatistics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _BATTLESTATISTICS_CUSTOMVALUESENTRY._options = None
  _BATTLESTATISTICS_CUSTOMVALUESENTRY._serialized_options = b'8\001'
  _globals['_BATTLESTATISTICS']._serialized_start=74
  _globals['_BATTLESTATISTICS']._serialized_end=565
  _globals['_BATTLESTATISTICS_CUSTOMVALUESENTRY']._serialized_start=514
  _globals['_BATTLESTATISTICS_CUSTOMVALUESENTRY']._serialized_end=565
# @@protoc_insertion_point(module_scope)
