# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleEndStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x42\x61ttleEndStatus.proto*d\n\x0f\x42\x61ttleEndStatus\x12\x13\n\x0f\x42\x41TTLE_END_NONE\x10\x00\x12\x12\n\x0e\x42\x41TTLE_END_WIN\x10\x01\x12\x13\n\x0f\x42\x41TTLE_END_LOSE\x10\x02\x12\x13\n\x0f\x42\x41TTLE_END_QUIT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattleEndStatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATTLEENDSTATUS']._serialized_start=25
  _globals['_BATTLEENDSTATUS']._serialized_end=125
# @@protoc_insertion_point(module_scope)
