# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleEventBattleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattleEventInitedData_pb2 as BattleEventInitedData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x42\x61ttleEventBattleInfo.proto\x1a\x1b\x42\x61ttleEventInitedData.proto\"X\n\x15\x42\x61ttleEventBattleInfo\x12\x17\n\x0f\x62\x61ttle_event_id\x18\x01 \x01(\r\x12&\n\x06status\x18\x02 \x01(\x0b\x32\x16.BattleEventInitedDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattleEventBattleInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATTLEEVENTBATTLEINFO']._serialized_start=60
  _globals['_BATTLEEVENTBATTLEINFO']._serialized_end=148
# @@protoc_insertion_point(module_scope)
