# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleOp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x42\x61ttleOp.proto\"\xa4\x01\n\x08\x42\x61ttleOp\x12\x14\n\x0cturn_counter\x18\x01 \x01(\r\x12\r\n\x05state\x18\x02 \x01(\r\x12\x18\n\x10\x61\x63tion_entity_id\x18\x03 \x01(\r\x12\x18\n\x10target_entity_id\x18\x04 \x01(\r\x12\x0f\n\x07op_type\x18\x05 \x01(\r\x12\x13\n\x0bskill_index\x18\x06 \x01(\r\x12\x19\n\x11operation_counter\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattleOp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATTLEOP']._serialized_start=19
  _globals['_BATTLEOP']._serialized_end=183
# @@protoc_insertion_point(module_scope)
