# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattlePassInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x42\x61ttlePassInfoNotify.proto\"\xda\x03\n\x14\x42\x61ttlePassInfoNotify\x12\x36\n\x0c\x62p_tier_type\x18\x0b \x01(\x0e\x32 .BattlePassInfoNotify.BpTierType\x12\r\n\x05level\x18\r \x01(\r\x12\x0b\n\x03\x65xp\x18\x0c \x01(\r\x12\x11\n\tcur_bp_id\x18\x05 \x01(\r\x12\x1c\n\x14\x63ur_week_add_exp_sum\x18\x01 \x01(\r\x12\x19\n\x11taken_free_reward\x18\n \x01(\x04\x12\"\n\x1ataken_free_extended_reward\x18\x08 \x01(\x04\x12%\n\x1dtaken_premium_optional_reward\x18\x02 \x01(\x04\x12%\n\x1dtaken_premium_extended_reward\x18\x04 \x01(\x04\x12\x1d\n\x15taken_premium_reward2\x18\x03 \x01(\x04\x12\x1d\n\x15taken_premium_reward1\x18\t \x01(\x04\"r\n\nBpTierType\x12\x15\n\x11\x42P_TIER_TYPE_NONE\x10\x00\x12\x15\n\x11\x42P_TIER_TYPE_FREE\x10\x01\x12\x1a\n\x16\x42P_TIER_TYPE_PREMIUM_1\x10\x02\x12\x1a\n\x16\x42P_TIER_TYPE_PREMIUM_2\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattlePassInfoNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATTLEPASSINFONOTIFY']._serialized_start=31
  _globals['_BATTLEPASSINFONOTIFY']._serialized_end=505
  _globals['_BATTLEPASSINFONOTIFY_BPTIERTYPE']._serialized_start=391
  _globals['_BATTLEPASSINFONOTIFY_BPTIERTYPE']._serialized_end=505
# @@protoc_insertion_point(module_scope)
