# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleBuff.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x42\x61ttleBuff.proto\"\xd5\x01\n\nBattleBuff\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05level\x18\x02 \x01(\r\x12\x10\n\x08owner_id\x18\x03 \x01(\r\x12\x11\n\twave_flag\x18\x04 \x01(\r\x12\x19\n\x11target_index_list\x18\x05 \x03(\r\x12\x36\n\x0e\x64ynamic_values\x18\x06 \x03(\x0b\x32\x1e.BattleBuff.DynamicValuesEntry\x1a\x34\n\x12\x44ynamicValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattleBuff_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _BATTLEBUFF_DYNAMICVALUESENTRY._options = None
  _BATTLEBUFF_DYNAMICVALUESENTRY._serialized_options = b'8\001'
  _globals['_BATTLEBUFF']._serialized_start=21
  _globals['_BATTLEBUFF']._serialized_end=234
  _globals['_BATTLEBUFF_DYNAMICVALUESENTRY']._serialized_start=182
  _globals['_BATTLEBUFF_DYNAMICVALUESENTRY']._serialized_end=234
# @@protoc_insertion_point(module_scope)
