# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleEventInitedData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SpBarInfo_pb2 as SpBarInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x42\x61ttleEventInitedData.proto\x1a\x0fSpBarInfo.proto\"3\n\x15\x42\x61ttleEventInitedData\x12\x1a\n\x06sp_bar\x18\x02 \x01(\x0b\x32\n.SpBarInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattleEventInitedData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATTLEEVENTINITEDDATA']._serialized_start=48
  _globals['_BATTLEEVENTINITEDDATA']._serialized_end=99
# @@protoc_insertion_point(module_scope)
