# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleAvatar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattleEquipment_pb2 as BattleEquipment__pb2
import AvatarSkillTree_pb2 as AvatarSkillTree__pb2
import AvatarType_pb2 as AvatarType__pb2
import BattleRelic_pb2 as BattleRelic__pb2
import SpBarInfo_pb2 as SpBarInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x42\x61ttleAvatar.proto\x1a\x15\x42\x61ttleEquipment.proto\x1a\x15\x41vatarSkillTree.proto\x1a\x10\x41vatarType.proto\x1a\x11\x42\x61ttleRelic.proto\x1a\x0fSpBarInfo.proto\"\xc2\x02\n\x0c\x42\x61ttleAvatar\x12 \n\x0b\x61vatar_type\x18\x01 \x01(\x0e\x32\x0b.AvatarType\x12\n\n\x02id\x18\x02 \x01(\r\x12\r\n\x05level\x18\x03 \x01(\r\x12\x0c\n\x04rank\x18\x04 \x01(\r\x12\r\n\x05index\x18\x05 \x01(\r\x12(\n\x0eskilltree_list\x18\x06 \x03(\x0b\x32\x10.AvatarSkillTree\x12(\n\x0e\x65quipment_list\x18\x07 \x03(\x0b\x32\x10.BattleEquipment\x12\n\n\x02hp\x18\x08 \x01(\r\x12\x11\n\tpromotion\x18\n \x01(\r\x12 \n\nrelic_list\x18\x0b \x03(\x0b\x32\x0c.BattleRelic\x12\x13\n\x0bworld_level\x18\x0c \x01(\r\x12\x12\n\nassist_uid\x18\r \x01(\r\x12\x1a\n\x06sp_bar\x18\x10 \x01(\x0b\x32\n.SpBarInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattleAvatar_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATTLEAVATAR']._serialized_start=123
  _globals['_BATTLEAVATAR']._serialized_end=445
# @@protoc_insertion_point(module_scope)
