# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BattleTargetList.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattleTarget_pb2 as BattleTarget__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x42\x61ttleTargetList.proto\x1a\x12\x42\x61ttleTarget.proto\"=\n\x10\x42\x61ttleTargetList\x12)\n\x12\x62\x61ttle_target_list\x18\x01 \x03(\x0b\x32\r.BattleTargetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BattleTargetList_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BATTLETARGETLIST']._serialized_start=46
  _globals['_BATTLETARGETLIST']._serialized_end=107
# @@protoc_insertion_point(module_scope)
