# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BoardDataSync.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HeadIcon_pb2 as HeadIcon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x42oardDataSync.proto\x1a\x0eHeadIcon.proto\"N\n\rBoardDataSync\x12\x11\n\tsignature\x18\x0c \x01(\t\x12*\n\x17unlocked_head_icon_list\x18\r \x03(\x0b\x32\t.HeadIconb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BoardDataSync_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOARDDATASYNC']._serialized_start=39
  _globals['_BOARDDATASYNC']._serialized_end=117
# @@protoc_insertion_point(module_scope)
