# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BuffInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x42uffInfo.proto\"\xe5\x01\n\x08\x42uffInfo\x12\r\n\x05\x63ount\x18\r \x01(\r\x12\x11\n\tlife_time\x18\x03 \x01(\x02\x12\x16\n\x0e\x62\x61se_avatar_id\x18\t \x01(\r\x12\x0f\n\x07\x62uff_id\x18\x04 \x01(\r\x12\x34\n\x0e\x64ynamic_values\x18\x05 \x03(\x0b\x32\x1c.BuffInfo.DynamicValuesEntry\x12\x13\n\x0b\x61\x64\x64_time_ms\x18\x01 \x01(\x04\x12\r\n\x05level\x18\x0c \x01(\r\x1a\x34\n\x12\x44ynamicValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BuffInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _BUFFINFO_DYNAMICVALUESENTRY._options = None
  _BUFFINFO_DYNAMICVALUESENTRY._serialized_options = b'8\001'
  _globals['_BUFFINFO']._serialized_start=19
  _globals['_BUFFINFO']._serialized_end=248
  _globals['_BUFFINFO_DYNAMICVALUESENTRY']._serialized_start=196
  _globals['_BUFFINFO_DYNAMICVALUESENTRY']._serialized_end=248
# @@protoc_insertion_point(module_scope)
