# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BuyGoodsScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x42uyGoodsScRsp.proto\x1a\x0eItemList.proto\"\x81\x01\n\rBuyGoodsScRsp\x12#\n\x10return_item_list\x18\x0e \x01(\x0b\x32\t.ItemList\x12\x0f\n\x07retcode\x18\x05 \x01(\r\x12\x0f\n\x07shop_id\x18\x03 \x01(\r\x12\x10\n\x08goods_id\x18\x07 \x01(\r\x12\x17\n\x0fgoods_buy_times\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BuyGoodsScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BUYGOODSSCRSP']._serialized_start=40
  _globals['_BUYGOODSSCRSP']._serialized_end=169
# @@protoc_insertion_point(module_scope)
