# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BuyGoodsCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x42uyGoodsCsReq.proto\"V\n\rBuyGoodsCsReq\x12\x0f\n\x07shop_id\x18\r \x01(\r\x12\x11\n\tgoods_num\x18\x04 \x01(\r\x12\x0f\n\x07item_id\x18\x03 \x01(\r\x12\x10\n\x08goods_id\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BuyGoodsCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BUYGOODSCSREQ']._serialized_start=23
  _globals['_BUYGOODSCSREQ']._serialized_end=109
# @@protoc_insertion_point(module_scope)
