# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Challenge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChallengeExtInfo_pb2 as ChallengeExtInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x43hallenge.proto\x1a\x16\x43hallengeExtInfo.proto\"z\n\tChallenge\x12\r\n\x05stars\x18\x03 \x01(\r\x12#\n\x08\x65xt_info\x18\x07 \x01(\x0b\x32\x11.ChallengeExtInfo\x12\x14\n\x0ctaken_reward\x18\n \x01(\r\x12\x14\n\x0c\x63hallenge_id\x18\r \x01(\r\x12\r\n\x05score\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Challenge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHALLENGE']._serialized_start=43
  _globals['_CHALLENGE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
