# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChallengeLineupNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ExtraLineupType_pb2 as ExtraLineupType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43hallengeLineupNotify.proto\x1a\x15\x45xtraLineupType.proto\"D\n\x15\x43hallengeLineupNotify\x12+\n\x11\x65xtra_lineup_type\x18\x0c \x01(\x0e\x32\x10.ExtraLineupTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChallengeLineupNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHALLENGELINEUPNOTIFY']._serialized_start=54
  _globals['_CHALLENGELINEUPNOTIFY']._serialized_end=122
# @@protoc_insertion_point(module_scope)
