# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChallengeBossSingleNodeInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ChallengeBossSingleNodeInfo.proto\"q\n\x1b\x43hallengeBossSingleNodeInfo\x12\x13\n\x0b\x44\x41IMOOEMHJF\x18\x0e \x01(\r\x12\x13\n\x0b\x42MIKMFLHMJD\x18\x05 \x01(\x08\x12\x13\n\x0bKLJPBAAGNFN\x18\x0b \x01(\r\x12\x13\n\x0bNAGJMPMHMMC\x18\x07 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChallengeBossSingleNodeInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHALLENGEBOSSSINGLENODEINFO']._serialized_start=37
  _globals['_CHALLENGEBOSSSINGLENODEINFO']._serialized_end=150
# @@protoc_insertion_point(module_scope)
