# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChallengeInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ExtraLineupType_pb2 as ExtraLineupType__pb2
import ChallengeStoryInfo_pb2 as ChallengeStoryInfo__pb2
import ChallengeStatus_pb2 as ChallengeStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x43hallengeInfo.proto\x1a\x15\x45xtraLineupType.proto\x1a\x18\x43hallengeStoryInfo.proto\x1a\x15\x43hallengeStatus.proto\"\xd4\x01\n\rChallengeInfo\x12\x14\n\x0c\x63hallenge_id\x18\x0f \x01(\r\x12\'\n\nstory_info\x18\x04 \x01(\x0b\x32\x13.ChallengeStoryInfo\x12\r\n\x05score\x18\x03 \x01(\r\x12\x13\n\x0bround_count\x18\n \x01(\r\x12\x11\n\tscore_two\x18\t \x01(\r\x12+\n\x11\x65xtra_lineup_type\x18\x0e \x01(\x0e\x32\x10.ExtraLineupType\x12 \n\x06status\x18\r \x01(\x0e\x32\x10.ChallengeStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChallengeInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHALLENGEINFO']._serialized_start=96
  _globals['_CHALLENGEINFO']._serialized_end=308
# @@protoc_insertion_point(module_scope)
