# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChallengeExtInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChallengeBossInfo_pb2 as ChallengeBossInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43hallengeExtInfo.proto\x1a\x17\x43hallengeBossInfo.proto\"9\n\x10\x43hallengeExtInfo\x12%\n\tboss_info\x18\x07 \x01(\x0b\x32\x12.ChallengeBossInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChallengeExtInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHALLENGEEXTINFO']._serialized_start=51
  _globals['_CHALLENGEEXTINFO']._serialized_end=108
# @@protoc_insertion_point(module_scope)
