# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChallengeBossInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChallengeBossSingleNodeInfo_pb2 as ChallengeBossSingleNodeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x43hallengeBossInfo.proto\x1a!ChallengeBossSingleNodeInfo.proto\"\xaf\x01\n\x11\x43hallengeBossInfo\x12\x30\n\nfirst_node\x18\x0f \x01(\x0b\x32\x1c.ChallengeBossSingleNodeInfo\x12\x0f\n\x07lineup1\x18\r \x03(\r\x12\x31\n\x0bsecond_node\x18\x0c \x01(\x0b\x32\x1c.ChallengeBossSingleNodeInfo\x12\x13\n\x0bPPNAGBNIOAO\x18\n \x01(\x08\x12\x0f\n\x07lineup2\x18\x02 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChallengeBossInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHALLENGEBOSSINFO']._serialized_start=63
  _globals['_CHALLENGEBOSSINFO']._serialized_end=238
# @@protoc_insertion_point(module_scope)
