# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChallengeStoryInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChallengeStoryBuffInfo_pb2 as ChallengeStoryBuffInfo__pb2
import ChallengeBossBuffInfo_pb2 as ChallengeBossBuffInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43hallengeStoryInfo.proto\x1a\x1c\x43hallengeStoryBuffInfo.proto\x1a\x1b\x43hallengeBossBuffInfo.proto\"v\n\x12\x43hallengeStoryInfo\x12\x30\n\x0f\x63ur_story_buffs\x18\n \x01(\x0b\x32\x17.ChallengeStoryBuffInfo\x12.\n\x0e\x63ur_boss_buffs\x18\x02 \x01(\x0b\x32\x16.ChallengeBossBuffInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChallengeStoryInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHALLENGESTORYINFO']._serialized_start=87
  _globals['_CHALLENGESTORYINFO']._serialized_end=205
# @@protoc_insertion_point(module_scope)
