# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatType.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x43hatType.proto*J\n\x08\x43hatType\x12\x12\n\x0e\x43HAT_TYPE_NONE\x10\x00\x12\x15\n\x11\x43HAT_TYPE_PRIVATE\x10\x01\x12\x13\n\x0f\x43HAT_TYPE_GROUP\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChatType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHATTYPE']._serialized_start=18
  _globals['_CHATTYPE']._serialized_end=92
# @@protoc_insertion_point(module_scope)
