# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueNousStoryInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x43hessRogueNousStoryInfo.proto\"\xbf\x01\n\x17\x43hessRogueNousStoryInfo\x12\x13\n\x0bHCPCJBDBBGC\x18\x01 \x03(\r\x12\x13\n\x0bINPDLILFOCO\x18\t \x03(\r\x12\x14\n\x0csub_story_id\x18\x07 \x01(\r\x12\x13\n\x0b\x43KEKKMGIHKJ\x18\x08 \x01(\x08\x12\x13\n\x0b\x41HOJIDMLFPE\x18\x0c \x01(\x08\x12\x13\n\x0b\x43MHLEEKNFKH\x18\x04 \x03(\r\x12\x10\n\x08story_id\x18\x03 \x01(\r\x12\x13\n\x0b\x41\x43LGLHEFFON\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueNousStoryInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUENOUSSTORYINFO']._serialized_start=34
  _globals['_CHESSROGUENOUSSTORYINFO']._serialized_end=225
# @@protoc_insertion_point(module_scope)
