# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueRollDiceScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueNousDice_pb2 as ChessRogueNousDice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x43hessRogueRollDiceScRsp.proto\x1a\x18\x43hessRogueNousDice.proto\"g\n\x17\x43hessRogueRollDiceScRsp\x12\x0f\n\x07retcode\x18\n \x01(\r\x12\x13\n\x0bOHNDNDDKAEG\x18\x0b \x01(\r\x12&\n\tnous_dice\x18\x06 \x01(\x0b\x32\x13.ChessRogueNousDiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueRollDiceScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUEROLLDICESCRSP']._serialized_start=59
  _globals['_CHESSROGUEROLLDICESCRSP']._serialized_end=162
# @@protoc_insertion_point(module_scope)
