# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueItemInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43hessRogueItemInfo.proto\"q\n\x12\x43hessRogueItemInfo\x12-\n\x05items\x18\x04 \x03(\x0b\x32\x1e.ChessRogueItemInfo.ItemsEntry\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueItemInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _CHESSROGUEITEMINFO_ITEMSENTRY._options = None
  _CHESSROGUEITEMINFO_ITEMSENTRY._serialized_options = b'8\001'
  _globals['_CHESSROGUEITEMINFO']._serialized_start=28
  _globals['_CHESSROGUEITEMINFO']._serialized_end=141
  _globals['_CHESSROGUEITEMINFO_ITEMSENTRY']._serialized_start=97
  _globals['_CHESSROGUEITEMINFO_ITEMSENTRY']._serialized_end=141
# @@protoc_insertion_point(module_scope)
