# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueCellInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueCell_pb2 as ChessRogueCell__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43hessRogueCellInfo.proto\x1a\x14\x43hessRogueCell.proto\"I\n\x12\x43hessRogueCellInfo\x12\x1e\n\x05query\x18\x01 \x03(\x0b\x32\x0f.ChessRogueCell\x12\x13\n\x0b\x42IEJGDGAOBL\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueCellInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUECELLINFO']._serialized_start=50
  _globals['_CHESSROGUECELLINFO']._serialized_end=123
# @@protoc_insertion_point(module_scope)
