# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueCurrentInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueNousStoryInfo_pb2 as ChessRogueNousStoryInfo__pb2
import ChessRogueAvatarInfo_pb2 as ChessRogueAvatarInfo__pb2
import ChessRogueVirtualItemInfo_pb2 as ChessRogueVirtualItemInfo__pb2
import RogueCommonPendingAction_pb2 as RogueCommonPendingAction__pb2
import ChessRogueBuffInfo_pb2 as ChessRogueBuffInfo__pb2
import ChessRogueMiracleInfo_pb2 as ChessRogueMiracleInfo__pb2
import ChessRogueNousDice_pb2 as ChessRogueNousDice__pb2
import ChessRogueNousValue_pb2 as ChessRogueNousValue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43hessRogueCurrentInfo.proto\x1a\x1d\x43hessRogueNousStoryInfo.proto\x1a\x1a\x43hessRogueAvatarInfo.proto\x1a\x1f\x43hessRogueVirtualItemInfo.proto\x1a\x1eRogueCommonPendingAction.proto\x1a\x18\x43hessRogueBuffInfo.proto\x1a\x1b\x43hessRogueMiracleInfo.proto\x1a\x18\x43hessRogueNousDice.proto\x1a\x19\x43hessRogueNousValue.proto\"\xa3\x03\n\x15\x43hessRogueCurrentInfo\x12,\n\nstory_info\x18\n \x01(\x0b\x32\x18.ChessRogueNousStoryInfo\x12\x30\n\x11rogue_avatar_info\x18\t \x01(\x0b\x32\x15.ChessRogueAvatarInfo\x12\x18\n\x10rogue_version_id\x18\x06 \x01(\r\x12\x35\n\x11virtual_item_info\x18\x04 \x03(\x0b\x32\x1a.ChessRogueVirtualItemInfo\x12&\n\tbuff_info\x18\x0c \x01(\x0b\x32\x13.ChessRogueBuffInfo\x12\x31\n\x0epending_action\x18\x0b \x01(\x0b\x32\x19.RogueCommonPendingAction\x12(\n\nnous_value\x18\x01 \x01(\x0b\x32\x14.ChessRogueNousValue\x12,\n\x0cmiracle_info\x18\x0e \x01(\x0b\x32\x16.ChessRogueMiracleInfo\x12&\n\tdice_info\x18\x0f \x01(\x0b\x32\x13.ChessRogueNousDiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueCurrentInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUECURRENTINFO']._serialized_start=264
  _globals['_CHESSROGUECURRENTINFO']._serialized_end=683
# @@protoc_insertion_point(module_scope)
