# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueNousEditDiceScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueNousDiceInfo_pb2 as ChessRogueNousDiceInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ChessRogueNousEditDiceScRsp.proto\x1a\x1c\x43hessRogueNousDiceInfo.proto\"Z\n\x1b\x43hessRogueNousEditDiceScRsp\x12\x0f\n\x07retcode\x18\x0b \x01(\r\x12*\n\tdice_info\x18\r \x01(\x0b\x32\x17.ChessRogueNousDiceInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueNousEditDiceScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUENOUSEDITDICESCRSP']._serialized_start=67
  _globals['_CHESSROGUENOUSEDITDICESCRSP']._serialized_end=157
# @@protoc_insertion_point(module_scope)
