# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueSelectCellScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x43hessRogueSelectCellScRsp.proto\"=\n\x19\x43hessRogueSelectCellScRsp\x12\x0f\n\x07\x63\x65ll_id\x18\x0e \x01(\r\x12\x0f\n\x07retcode\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueSelectCellScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUESELECTCELLSCRSP']._serialized_start=35
  _globals['_CHESSROGUESELECTCELLSCRSP']._serialized_end=96
# @@protoc_insertion_point(module_scope)
