# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueAvatarInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueAvatar_pb2 as ChessRogueAvatar__pb2
import RogueAvatarReviveCost_pb2 as RogueAvatarReviveCost__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43hessRogueAvatarInfo.proto\x1a\x16\x43hessRogueAvatar.proto\x1a\x1bRogueAvatarReviveCost.proto\"r\n\x14\x43hessRogueAvatarInfo\x12+\n\x0brevive_cost\x18\x03 \x01(\x0b\x32\x16.RogueAvatarReviveCost\x12-\n\x12\x63hess_rogue_avatar\x18\x05 \x03(\x0b\x32\x11.ChessRogueAvatarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueAvatarInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUEAVATARINFO']._serialized_start=83
  _globals['_CHESSROGUEAVATARINFO']._serialized_end=197
# @@protoc_insertion_point(module_scope)
