# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueBuffInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueBuffData_pb2 as ChessRogueBuffData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43hessRogueBuffInfo.proto\x1a\x18\x43hessRogueBuffData.proto\"<\n\x12\x43hessRogueBuffInfo\x12&\n\tbuff_data\x18\x0c \x01(\x0b\x32\x13.ChessRogueBuffDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueBuffInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUEBUFFINFO']._serialized_start=54
  _globals['_CHESSROGUEBUFFINFO']._serialized_end=114
# @@protoc_insertion_point(module_scope)
