# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LineupInfo_pb2 as LineupInfo__pb2
import SceneInfo_pb2 as SceneInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x43hessRogueInfo.proto\x1a\x10LineupInfo.proto\x1a\x0fSceneInfo.proto\"H\n\x0e\x43hessRogueInfo\x12\x1b\n\x06lineup\x18\x07 \x01(\x0b\x32\x0b.LineupInfo\x12\x19\n\x05scene\x18\x05 \x01(\x0b\x32\n.SceneInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUEINFO']._serialized_start=59
  _globals['_CHESSROGUEINFO']._serialized_end=131
# @@protoc_insertion_point(module_scope)
