# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueVirtualItemInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueBuffInfo_pb2 as ChessRogueBuffInfo__pb2
import ChessRogueMiracleInfo_pb2 as ChessRogueMiracleInfo__pb2
import ChessRogueItemInfo_pb2 as ChessRogueItemInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x43hessRogueVirtualItemInfo.proto\x1a\x18\x43hessRogueBuffInfo.proto\x1a\x1b\x43hessRogueMiracleInfo.proto\x1a\x18\x43hessRogueItemInfo.proto\"\x99\x01\n\x19\x43hessRogueVirtualItemInfo\x12&\n\tbuff_info\x18\x06 \x01(\x0b\x32\x13.ChessRogueBuffInfo\x12,\n\x0cmiracle_info\x18\n \x01(\x0b\x32\x16.ChessRogueMiracleInfo\x12&\n\titem_info\x18\x0b \x01(\x0b\x32\x13.ChessRogueItemInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueVirtualItemInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUEVIRTUALITEMINFO']._serialized_start=117
  _globals['_CHESSROGUEVIRTUALITEMINFO']._serialized_end=270
# @@protoc_insertion_point(module_scope)
