# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueCell.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x43hessRogueCell.proto\"\xf3\x01\n\x0e\x43hessRogueCell\x12\x13\n\x0bJLOBGDKNJLN\x18\n \x01(\r\x12\x13\n\x0bNNMNHHPJBDB\x18\x02 \x01(\r\x12\x13\n\x0bis_unlocked\x18\x08 \x01(\x08\x12\x13\n\x0bPNKFAINKKCE\x18\x07 \x01(\r\x12\x13\n\x0b\x46OKKJJADPEA\x18\x05 \x01(\r\x12\x13\n\x0bNLBGDNLIONI\x18\x03 \x01(\r\x12\x13\n\x0bIIJOCONHKND\x18\x04 \x03(\r\x12\x13\n\x0b\x65ntrance_id\x18\x01 \x01(\r\x12\x13\n\x0bnew_room_id\x18\x0b \x01(\r\x12\x0f\n\x07\x63\x65ll_id\x18\t \x01(\r\x12\x13\n\x0bPMBLMGDFGAN\x18\x06 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueCell_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUECELL']._serialized_start=25
  _globals['_CHESSROGUECELL']._serialized_end=268
# @@protoc_insertion_point(module_scope)
