# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueMiracleData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueMiracle_pb2 as RogueMiracle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43hessRogueMiracleData.proto\x1a\x12RogueMiracle.proto\"<\n\x15\x43hessRogueMiracleData\x12#\n\x0cmiracle_list\x18\x0b \x03(\x0b\x32\r.RogueMiracleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueMiracleData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUEMIRACLEDATA']._serialized_start=51
  _globals['_CHESSROGUEMIRACLEDATA']._serialized_end=111
# @@protoc_insertion_point(module_scope)
