# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueUpdateMoneyInfoScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueMoneyInfo_pb2 as ChessRogueMoneyInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ChessRogueUpdateMoneyInfoScNotify.proto\x1a\x19\x43hessRogueMoneyInfo.proto\"M\n!ChessRogueUpdateMoneyInfoScNotify\x12(\n\nmoney_info\x18\x0c \x01(\x0b\x32\x14.ChessRogueMoneyInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueUpdateMoneyInfoScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUEUPDATEMONEYINFOSCNOTIFY']._serialized_start=70
  _globals['_CHESSROGUEUPDATEMONEYINFOSCNOTIFY']._serialized_end=147
# @@protoc_insertion_point(module_scope)
