# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueNousDiceInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueNousDiceSurfaceInfo_pb2 as ChessRogueNousDiceSurfaceInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43hessRogueNousDiceInfo.proto\x1a#ChessRogueNousDiceSurfaceInfo.proto\"\x9b\x01\n\x16\x43hessRogueNousDiceInfo\x12\x16\n\x0emax_difficulty\x18\x0e \x01(\r\x12\x34\n\x0c\x64ice_surface\x18\x02 \x03(\x0b\x32\x1e.ChessRogueNousDiceSurfaceInfo\x12\x16\n\x0e\x64ice_branch_id\x18\x05 \x01(\r\x12\x1b\n\x13question_difficulty\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueNousDiceInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUENOUSDICEINFO']._serialized_start=70
  _globals['_CHESSROGUENOUSDICEINFO']._serialized_end=225
# @@protoc_insertion_point(module_scope)
