# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueMiracleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueMiracleData_pb2 as ChessRogueMiracleData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43hessRogueMiracleInfo.proto\x1a\x1b\x43hessRogueMiracleData.proto\"E\n\x15\x43hessRogueMiracleInfo\x12,\n\x0cmiracle_data\x18\r \x01(\x0b\x32\x16.ChessRogueMiracleDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueMiracleInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUEMIRACLEINFO']._serialized_start=60
  _globals['_CHESSROGUEMIRACLEINFO']._serialized_end=129
# @@protoc_insertion_point(module_scope)
