# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueStartScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChessRogueCurrentInfo_pb2 as ChessRogueCurrentInfo__pb2
import LineupInfo_pb2 as LineupInfo__pb2
import ChessRogueCellInfo_pb2 as ChessRogueCellInfo__pb2
import SceneInfo_pb2 as SceneInfo__pb2
import ChessRogueInfo_pb2 as ChessRogueInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43hessRogueStartScRsp.proto\x1a\x1b\x43hessRogueCurrentInfo.proto\x1a\x10LineupInfo.proto\x1a\x18\x43hessRogueCellInfo.proto\x1a\x0fSceneInfo.proto\x1a\x14\x43hessRogueInfo.proto\"\xe0\x01\n\x14\x43hessRogueStartScRsp\x12\x0f\n\x07retcode\x18\x02 \x01(\r\x12,\n\x0c\x63urrent_info\x18\x01 \x01(\x0b\x32\x16.ChessRogueCurrentInfo\x12\x1b\n\x06lineup\x18\x08 \x01(\x0b\x32\x0b.LineupInfo\x12&\n\tcell_info\x18\r \x01(\x0b\x32\x13.ChessRogueCellInfo\x12\x19\n\x05scene\x18\x0f \x01(\x0b\x32\n.SceneInfo\x12)\n\x10\x63hess_rogue_info\x18\x0e \x01(\x0b\x32\x0f.ChessRogueInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueStartScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUESTARTSCRSP']._serialized_start=143
  _globals['_CHESSROGUESTARTSCRSP']._serialized_end=367
# @@protoc_insertion_point(module_scope)
