# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChessRogueBuffData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuffData_pb2 as RogueBuffData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43hessRogueBuffData.proto\x1a\x13RogueBuffData.proto\"7\n\x12\x43hessRogueBuffData\x12!\n\tbuff_list\x18\x0c \x03(\x0b\x32\x0e.RogueBuffDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChessRogueBuffData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSROGUEBUFFDATA']._serialized_start=49
  _globals['_CHESSROGUEBUFFDATA']._serialized_end=104
# @@protoc_insertion_point(module_scope)
