# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMail.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43lientMail.proto\x1a\x0eItemList.proto\"\xc3\x01\n\nClientMail\x12\x0f\n\x07is_read\x18\x01 \x01(\x08\x12\x13\n\x0b\x65xpire_time\x18\x08 \x01(\x03\x12\x13\n\x0btemplate_id\x18\x05 \x01(\r\x12\x1d\n\nattachment\x18\x0c \x01(\x0b\x32\t.ItemList\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x06 \x01(\t\x12\x11\n\tpara_list\x18\t \x03(\t\x12\n\n\x02id\x18\x07 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x0b \x01(\t\x12\x0c\n\x04time\x18\x0e \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientMail_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTMAIL']._serialized_start=37
  _globals['_CLIENTMAIL']._serialized_end=232
# @@protoc_insertion_point(module_scope)
