# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ComposeItemCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemCostList_pb2 as ItemCostList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43omposeItemCsReq.proto\x1a\x12ItemCostList.proto\"_\n\x10\x43omposeItemCsReq\x12\r\n\x05\x63ount\x18\n \x01(\r\x12(\n\x11\x63ompose_item_list\x18\x08 \x01(\x0b\x32\r.ItemCostList\x12\x12\n\ncompose_id\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ComposeItemCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMPOSEITEMCSREQ']._serialized_start=46
  _globals['_COMPOSEITEMCSREQ']._serialized_end=141
# @@protoc_insertion_point(module_scope)
