# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ComposeSelectedRelicScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x43omposeSelectedRelicScRsp.proto\x1a\x0eItemList.proto\"e\n\x19\x43omposeSelectedRelicScRsp\x12#\n\x10return_item_list\x18\x07 \x01(\x0b\x32\t.ItemList\x12\x12\n\ncompose_id\x18\n \x01(\r\x12\x0f\n\x07retcode\x18\r \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ComposeSelectedRelicScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMPOSESELECTEDRELICSCRSP']._serialized_start=51
  _globals['_COMPOSESELECTEDRELICSCRSP']._serialized_end=152
# @@protoc_insertion_point(module_scope)
