# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentPackageInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ContentPackageStatus_pb2 as ContentPackageStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43ontentPackageInfo.proto\x1a\x1a\x43ontentPackageStatus.proto\"O\n\x12\x43ontentPackageInfo\x12\x12\n\ncontent_id\x18\x0c \x01(\r\x12%\n\x06status\x18\x03 \x01(\x0e\x32\x15.ContentPackageStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContentPackageInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTENTPACKAGEINFO']._serialized_start=56
  _globals['_CONTENTPACKAGEINFO']._serialized_end=135
# @@protoc_insertion_point(module_scope)
