# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentPackageData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ContentPackageInfo_pb2 as ContentPackageInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43ontentPackageData.proto\x1a\x18\x43ontentPackageInfo.proto\"_\n\x12\x43ontentPackageData\x12\x31\n\x14\x63ontent_package_list\x18\t \x03(\x0b\x32\x13.ContentPackageInfo\x12\x16\n\x0e\x63ur_content_id\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContentPackageData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTENTPACKAGEDATA']._serialized_start=54
  _globals['_CONTENTPACKAGEDATA']._serialized_end=149
# @@protoc_insertion_point(module_scope)
