# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentPackageStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43ontentPackageStatus.proto*\x97\x01\n\x14\x43ontentPackageStatus\x12\x1d\n\x19\x43ontentPackageStatus_None\x10\x00\x12\x1d\n\x19\x43ontentPackageStatus_Init\x10\x01\x12\x1e\n\x1a\x43ontentPackageStatus_Doing\x10\x02\x12!\n\x1d\x43ontentPackageStatus_Finished\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContentPackageStatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTENTPACKAGESTATUS']._serialized_start=31
  _globals['_CONTENTPACKAGESTATUS']._serialized_end=182
# @@protoc_insertion_point(module_scope)
