# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentPackageGetDataScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ContentPackageData_pb2 as ContentPackageData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ContentPackageGetDataScRsp.proto\x1a\x18\x43ontentPackageData.proto\"P\n\x1a\x43ontentPackageGetDataScRsp\x12!\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x13.ContentPackageData\x12\x0f\n\x07retcode\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContentPackageGetDataScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTENTPACKAGEGETDATASCRSP']._serialized_start=62
  _globals['_CONTENTPACKAGEGETDATASCRSP']._serialized_end=142
# @@protoc_insertion_point(module_scope)
