# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DailyActivityInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x44\x61ilyActivityInfo.proto\"i\n\x11\x44\x61ilyActivityInfo\x12\x1a\n\x12\x64\x61ily_active_point\x18\x07 \x01(\r\x12\x13\n\x0bworld_level\x18\t \x01(\r\x12\x14\n\x0cis_has_taken\x18\x04 \x01(\x08\x12\r\n\x05level\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DailyActivityInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DAILYACTIVITYINFO']._serialized_start=27
  _globals['_DAILYACTIVITYINFO']._serialized_end=132
# @@protoc_insertion_point(module_scope)
