# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DailyActiveInfoNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DailyActivityInfo_pb2 as DailyActivityInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x44\x61ilyActiveInfoNotify.proto\x1a\x17\x44\x61ilyActivityInfo.proto\"\x8c\x01\n\x15\x44\x61ilyActiveInfoNotify\x12\x1a\n\x12\x64\x61ily_active_point\x18\x04 \x01(\r\x12\"\n\x1a\x64\x61ily_active_quest_id_list\x18\x0f \x03(\r\x12\x33\n\x17\x64\x61ily_active_level_list\x18\x08 \x03(\x0b\x32\x12.DailyActivityInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DailyActiveInfoNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DAILYACTIVEINFONOTIFY']._serialized_start=57
  _globals['_DAILYACTIVEINFONOTIFY']._serialized_end=197
# @@protoc_insertion_point(module_scope)
