# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeactivateFarmElementScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n DeactivateFarmElementScRsp.proto\"@\n\x1a\x44\x65\x61\x63tivateFarmElementScRsp\x12\x0f\n\x07retcode\x18\x04 \x01(\r\x12\x11\n\tentity_id\x18\x0b \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DeactivateFarmElementScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEACTIVATEFARMELEMENTSCRSP']._serialized_start=36
  _globals['_DEACTIVATEFARMELEMENTSCRSP']._serialized_end=100
# @@protoc_insertion_point(module_scope)
