# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeleteSocialEventServerCacheScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'DeleteSocialEventServerCacheScRsp.proto\"N\n!DeleteSocialEventServerCacheScRsp\x12\x18\n\x10ret_delete_cache\x18\x05 \x03(\r\x12\x0f\n\x07retcode\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DeleteSocialEventServerCacheScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DELETESOCIALEVENTSERVERCACHESCRSP']._serialized_start=43
  _globals['_DELETESOCIALEVENTSERVERCACHESCRSP']._serialized_end=121
# @@protoc_insertion_point(module_scope)
