# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeployRotaterScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RotaterData_pb2 as RotaterData__pb2
import RotatorEnergyInfo_pb2 as RotatorEnergyInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x44\x65ployRotaterScRsp.proto\x1a\x11RotaterData.proto\x1a\x17RotatorEnergyInfo.proto\"r\n\x12\x44\x65ployRotaterScRsp\x12\x0f\n\x07retcode\x18\x07 \x01(\r\x12\'\n\x0b\x65nergy_info\x18\n \x01(\x0b\x32\x12.RotatorEnergyInfo\x12\"\n\x0crotater_data\x18\x06 \x01(\x0b\x32\x0c.RotaterDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DeployRotaterScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEPLOYROTATERSCRSP']._serialized_start=72
  _globals['_DEPLOYROTATERSCRSP']._serialized_end=186
# @@protoc_insertion_point(module_scope)
