# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DevelopmentType.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x44\x65velopmentType.proto*\xa5\x03\n\x0f\x44\x65velopmentType\x12\x14\n\x10\x44\x45VELOPMENT_NONE\x10\x00\x12\x1c\n\x18\x44\x45VELOPMENT_ROGUE_COSMOS\x10\x01\x12\x1b\n\x17\x44\x45VELOPMENT_ROGUE_CHESS\x10\x02\x12 \n\x1c\x44\x45VELOPMENT_ROGUE_CHESS_NOUS\x10\x03\x12 \n\x1c\x44\x45VELOPMENT_MEMORY_CHALLENGE\x10\x04\x12\x1f\n\x1b\x44\x45VELOPMENT_STORY_CHALLENGE\x10\x05\x12\x1d\n\x19\x44\x45VELOPMENT_UNLOCK_AVATAR\x10\x06\x12 \n\x1c\x44\x45VELOPMENT_UNLOCK_EQUIPMENT\x10\x07\x12\x1e\n\x1a\x44\x45VELOPMENT_ACTIVITY_START\x10\x08\x12\x1c\n\x18\x44\x45VELOPMENT_ACTIVITY_END\x10\t\x12\x1e\n\x1a\x44\x45VELOPMENT_BOSS_CHALLENGE\x10\n\x12\x1b\n\x17\x44\x45VELOPMENT_ROGUE_TOURN\x10\x0b\x12 \n\x1c\x44\x45VELOPMENT_ROGUE_TOURN_WEEK\x10\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DevelopmentType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEVELOPMENTTYPE']._serialized_start=26
  _globals['_DEVELOPMENTTYPE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
