# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DialogueResult.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x44ialogueResult.proto\x1a\x0eItemList.proto\"X\n\x0e\x44ialogueResult\x12\x13\n\x0bHFHKBMGBJAN\x18\x02 \x01(\r\x12\x11\n\tevent_ids\x18\n \x03(\r\x12\x1e\n\x0bitem_result\x18\r \x01(\x0b\x32\t.ItemListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DialogueResult_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DIALOGUERESULT']._serialized_start=40
  _globals['_DIALOGUERESULT']._serialized_end=128
# @@protoc_insertion_point(module_scope)
