# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DiscardRelicCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x44iscardRelicCsReq.proto\"@\n\x11\x44iscardRelicCsReq\x12\x17\n\x0frelic_unique_id\x18\x03 \x01(\r\x12\x12\n\nis_discard\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DiscardRelicCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DISCARDRELICCSREQ']._serialized_start=27
  _globals['_DISCARDRELICCSREQ']._serialized_end=91
# @@protoc_insertion_point(module_scope)
