# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DisplayEquipmentInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x44isplayEquipmentInfo.proto\"`\n\x14\x44isplayEquipmentInfo\x12\x0b\n\x03\x65xp\x18\n \x01(\r\x12\x0c\n\x04rank\x18\t \x01(\r\x12\x0b\n\x03tid\x18\x0b \x01(\r\x12\x11\n\tpromotion\x18\x04 \x01(\r\x12\r\n\x05level\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DisplayEquipmentInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DISPLAYEQUIPMENTINFO']._serialized_start=30
  _globals['_DISPLAYEQUIPMENTINFO']._serialized_end=126
# @@protoc_insertion_point(module_scope)
