# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DisplayAvatarVec.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DisplayAvatar_pb2 as DisplayAvatar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x44isplayAvatarVec.proto\x1a\x13\x44isplayAvatar.proto\"S\n\x10\x44isplayAvatarVec\x12+\n\x13\x64isplay_avatar_list\x18\x0b \x03(\x0b\x32\x0e.DisplayAvatar\x12\x12\n\nis_display\x18\x0c \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DisplayAvatarVec_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DISPLAYAVATARVEC']._serialized_start=47
  _globals['_DISPLAYAVATARVEC']._serialized_end=130
# @@protoc_insertion_point(module_scope)
