# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DisplayRelicInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RelicAffix_pb2 as RelicAffix__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x44isplayRelicInfo.proto\x1a\x10RelicAffix.proto\"\x85\x01\n\x10\x44isplayRelicInfo\x12\x0b\n\x03\x65xp\x18\x04 \x01(\r\x12\x15\n\rmain_affix_id\x18\x0c \x01(\r\x12#\n\x0esub_affix_list\x18\t \x03(\x0b\x32\x0b.RelicAffix\x12\x0b\n\x03tid\x18\x08 \x01(\r\x12\x0c\n\x04slot\x18\x0b \x01(\r\x12\r\n\x05level\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DisplayRelicInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DISPLAYRELICINFO']._serialized_start=45
  _globals['_DISPLAYRELICINFO']._serialized_end=178
# @@protoc_insertion_point(module_scope)
