# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DoGachaScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GachaItem_pb2 as GachaItem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x44oGachaScRsp.proto\x1a\x0fGachaItem.proto\"~\n\x0c\x44oGachaScRsp\x12\x10\n\x08gacha_id\x18\n \x01(\r\x12\x13\n\x0b\x63\x65iling_num\x18\r \x01(\r\x12\x0f\n\x07retcode\x18\x08 \x01(\r\x12\x11\n\tgacha_num\x18\x0c \x01(\r\x12#\n\x0fgacha_item_list\x18\x01 \x03(\x0b\x32\n.GachaItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DoGachaScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOGACHASCRSP']._serialized_start=39
  _globals['_DOGACHASCRSP']._serialized_end=165
# @@protoc_insertion_point(module_scope)
