# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DoGachaInRollShopScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x44oGachaInRollShopScRsp.proto\x1a\x0eItemList.proto\"\x84\x01\n\x16\x44oGachaInRollShopScRsp\x12\x0f\n\x07retcode\x18\t \x01(\r\x12\x19\n\x06reward\x18\r \x01(\x0b\x32\t.ItemList\x12\x13\n\x0bLEJJOJGNIHK\x18\x0c \x01(\r\x12\x14\n\x0croll_shop_id\x18\x0f \x01(\r\x12\x13\n\x0b\x41\x46MPDBBHCHM\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DoGachaInRollShopScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOGACHAINROLLSHOPSCRSP']._serialized_start=49
  _globals['_DOGACHAINROLLSHOPSCRSP']._serialized_end=181
# @@protoc_insertion_point(module_scope)
