# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DoGachaCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x44oGachaCsReq.proto\"a\n\x0c\x44oGachaCsReq\x12\x10\n\x08gacha_id\x18\x07 \x01(\r\x12\x11\n\tgacha_num\x18\n \x01(\r\x12\x16\n\x0esimulate_magic\x18\r \x01(\r\x12\x14\n\x0cgacha_random\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DoGachaCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOGACHACSREQ']._serialized_start=22
  _globals['_DOGACHACSREQ']._serialized_end=119
# @@protoc_insertion_point(module_scope)
