# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DressRelicAvatarCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RelicParam_pb2 as RelicParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x44ressRelicAvatarCsReq.proto\x1a\x10RelicParam.proto\"Q\n\x15\x44ressRelicAvatarCsReq\x12\x17\n\x0f\x65quip_avatar_id\x18\x02 \x01(\r\x12\x1f\n\nparam_list\x18\x01 \x03(\x0b\x32\x0b.RelicParamb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DressRelicAvatarCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DRESSRELICAVATARCSREQ']._serialized_start=49
  _globals['_DRESSRELICAVATARCSREQ']._serialized_end=130
# @@protoc_insertion_point(module_scope)
