# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DressAvatarCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x44ressAvatarCsReq.proto\"H\n\x10\x44ressAvatarCsReq\x12\x17\n\x0f\x65quip_avatar_id\x18\x02 \x01(\r\x12\x1b\n\x13\x65quipment_unique_id\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DressAvatarCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DRESSAVATARCSREQ']._serialized_start=26
  _globals['_DRESSAVATARCSREQ']._serialized_end=98
# @@protoc_insertion_point(module_scope)
