# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EnterMapRotationRegionScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MotionInfo_pb2 as MotionInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!EnterMapRotationRegionScRsp.proto\x1a\x10MotionInfo.proto\"g\n\x1b\x45nterMapRotationRegionScRsp\x12\x1b\n\x06motion\x18\t \x01(\x0b\x32\x0b.MotionInfo\x12\x0f\n\x07retcode\x18\x0b \x01(\r\x12\x1a\n\x12\x63lient_pos_version\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EnterMapRotationRegionScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTERMAPROTATIONREGIONSCRSP']._serialized_start=55
  _globals['_ENTERMAPROTATIONREGIONSCRSP']._serialized_end=158
# @@protoc_insertion_point(module_scope)
