# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EnterMapRotationRegionCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MotionInfo_pb2 as MotionInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!EnterMapRotationRegionCsReq.proto\x1a\x10MotionInfo.proto\":\n\x1b\x45nterMapRotationRegionCsReq\x12\x1b\n\x06motion\x18\x05 \x01(\x0b\x32\x0b.MotionInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EnterMapRotationRegionCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTERMAPROTATIONREGIONCSREQ']._serialized_start=55
  _globals['_ENTERMAPROTATIONREGIONCSREQ']._serialized_end=113
# @@protoc_insertion_point(module_scope)
