# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EnterSceneReason.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x45nterSceneReason.proto*\x7f\n\x10\x45nterSceneReason\x12\x1b\n\x17\x45NTER_SCENE_REASON_NONE\x10\x00\x12(\n$ENTER_SCENE_REASON_CHALLENGE_TIMEOUT\x10\x01\x12$\n ENTER_SCENE_REASON_ROGUE_TIMEOUT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EnterSceneReason_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTERSCENEREASON']._serialized_start=26
  _globals['_ENTERSCENEREASON']._serialized_end=153
# @@protoc_insertion_point(module_scope)
