# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EntityBuffInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BuffInfo_pb2 as BuffInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x45ntityBuffInfo.proto\x1a\x0e\x42uffInfo.proto\"A\n\x0e\x45ntityBuffInfo\x12\x1c\n\tbuff_list\x18\x04 \x03(\x0b\x32\t.BuffInfo\x12\x11\n\tentity_id\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EntityBuffInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTITYBUFFINFO']._serialized_start=40
  _globals['_ENTITYBUFFINFO']._serialized_end=105
# @@protoc_insertion_point(module_scope)
