# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EntityBuffChangeInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BuffInfo_pb2 as BuffInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x45ntityBuffChangeInfo.proto\x1a\x0e\x42uffInfo.proto\"c\n\x14\x45ntityBuffChangeInfo\x12 \n\radd_buff_info\x18\r \x01(\x0b\x32\t.BuffInfo\x12\x16\n\x0eremove_buff_id\x18\x0f \x01(\r\x12\x11\n\tentity_id\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EntityBuffChangeInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTITYBUFFCHANGEINFO']._serialized_start=46
  _globals['_ENTITYBUFFCHANGEINFO']._serialized_end=145
# @@protoc_insertion_point(module_scope)
