# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExchangeGachaCeilingScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2
import GachaCeiling_pb2 as GachaCeiling__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x45xchangeGachaCeilingScRsp.proto\x1a\x0eItemList.proto\x1a\x12GachaCeiling.proto\"\xa0\x01\n\x19\x45xchangeGachaCeilingScRsp\x12%\n\x12transfer_item_list\x18\x06 \x01(\x0b\x32\t.ItemList\x12\x11\n\tavatar_id\x18\t \x01(\r\x12\x0f\n\x07retcode\x18\x01 \x01(\r\x12$\n\rgacha_ceiling\x18\x0e \x01(\x0b\x32\r.GachaCeiling\x12\x12\n\ngacha_type\x18\x0f \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExchangeGachaCeilingScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXCHANGEGACHACEILINGSCRSP']._serialized_start=72
  _globals['_EXCHANGEGACHACEILINGSCRSP']._serialized_end=232
# @@protoc_insertion_point(module_scope)
