# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExpUpEquipmentCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemCostList_pb2 as ItemCostList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x45xpUpEquipmentCsReq.proto\x1a\x12ItemCostList.proto\"Y\n\x13\x45xpUpEquipmentCsReq\x12\x1b\n\x13\x65quipment_unique_id\x18\x06 \x01(\r\x12%\n\x0eitem_cost_list\x18\x08 \x01(\x0b\x32\r.ItemCostListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExpUpEquipmentCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXPUPEQUIPMENTCSREQ']._serialized_start=49
  _globals['_EXPUPEQUIPMENTCSREQ']._serialized_end=138
# @@protoc_insertion_point(module_scope)
