# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExpUpRelicCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemCostList_pb2 as ItemCostList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45xpUpRelicCsReq.proto\x1a\x12ItemCostList.proto\"Q\n\x0f\x45xpUpRelicCsReq\x12\x17\n\x0frelic_unique_id\x18\x0b \x01(\r\x12%\n\x0eitem_cost_list\x18\x01 \x01(\x0b\x32\r.ItemCostListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExpUpRelicCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXPUPRELICCSREQ']._serialized_start=45
  _globals['_EXPUPRELICCSREQ']._serialized_end=126
# @@protoc_insertion_point(module_scope)
