# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExpUpRelicScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PileItem_pb2 as PileItem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45xpUpRelicScRsp.proto\x1a\x0ePileItem.proto\"G\n\x0f\x45xpUpRelicScRsp\x12\x0f\n\x07retcode\x18\x01 \x01(\r\x12#\n\x10return_item_list\x18\n \x03(\x0b\x32\t.PileItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExpUpRelicScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXPUPRELICSCRSP']._serialized_start=41
  _globals['_EXPUPRELICSCRSP']._serialized_end=112
# @@protoc_insertion_point(module_scope)
