# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtraLineupType.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45xtraLineupType.proto*\xbd\x02\n\x0f\x45xtraLineupType\x12\x0f\n\x0bLINEUP_NONE\x10\x00\x12\x14\n\x10LINEUP_CHALLENGE\x10\x01\x12\x10\n\x0cLINEUP_ROGUE\x10\x02\x12\x16\n\x12LINEUP_CHALLENGE_2\x10\x03\x12\x16\n\x12LINEUP_CHALLENGE_3\x10\x04\x12\x1a\n\x16LINEUP_ROGUE_CHALLENGE\x10\x05\x12\x16\n\x12LINEUP_STAGE_TRIAL\x10\x06\x12\x16\n\x12LINEUP_ROGUE_TRIAL\x10\x07\x12\x13\n\x0fLINEUP_ACTIVITY\x10\x08\x12\x16\n\x12LINEUP_BOXING_CLUB\x10\t\x12\x1b\n\x17LINEUP_TREASURE_DUNGEON\x10\x0b\x12\x16\n\x12LINEUP_CHESS_ROGUE\x10\x0c\x12\x13\n\x0fLINEUP_HELIOBUS\x10\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExtraLineupType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXTRALINEUPTYPE']._serialized_start=26
  _globals['_EXTRALINEUPTYPE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
