# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FarmStageGachaInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x46\x61rmStageGachaInfo.proto\"L\n\x12\x46\x61rmStageGachaInfo\x12\x10\n\x08gacha_id\x18\x01 \x01(\r\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x03\x12\x12\n\nbegin_time\x18\x0b \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FarmStageGachaInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FARMSTAGEGACHAINFO']._serialized_start=28
  _globals['_FARMSTAGEGACHAINFO']._serialized_end=104
# @@protoc_insertion_point(module_scope)
