# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FinishTalkMissionScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MissionCustomValueData_pb2 as MissionCustomValueData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x46inishTalkMissionScRsp.proto\x1a\x1cMissionCustomValueData.proto\"\x87\x01\n\x16\x46inishTalkMissionScRsp\x12\x16\n\x0esub_mission_id\x18\x03 \x01(\r\x12\x10\n\x08talk_str\x18\t \x01(\t\x12\x0f\n\x07retcode\x18\x05 \x01(\r\x12\x32\n\x11\x63ustom_value_list\x18\x07 \x03(\x0b\x32\x17.MissionCustomValueDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FinishTalkMissionScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FINISHTALKMISSIONSCRSP']._serialized_start=63
  _globals['_FINISHTALKMISSIONSCRSP']._serialized_end=198
# @@protoc_insertion_point(module_scope)
