# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FinishTalkMissionCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MissionCustomValueData_pb2 as MissionCustomValueData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x46inishTalkMissionCsReq.proto\x1a\x1cMissionCustomValueData.proto\"v\n\x16\x46inishTalkMissionCsReq\x12\x10\n\x08talk_str\x18\x02 \x01(\t\x12\x32\n\x11\x63ustom_value_list\x18\x05 \x03(\x0b\x32\x17.MissionCustomValueData\x12\x16\n\x0esub_mission_id\x18\x0b \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FinishTalkMissionCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FINISHTALKMISSIONCSREQ']._serialized_start=62
  _globals['_FINISHTALKMISSIONCSREQ']._serialized_end=180
# @@protoc_insertion_point(module_scope)
