# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendApplyInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SimpleInfo_pb2 as SimpleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x46riendApplyInfo.proto\x1a\x10SimpleInfo.proto\"3\n\x0f\x46riendApplyInfo\x12 \n\x0bsimple_info\x18\x0c \x01(\x0b\x32\x0b.SimpleInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FriendApplyInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRIENDAPPLYINFO']._serialized_start=43
  _globals['_FRIENDAPPLYINFO']._serialized_end=94
# @@protoc_insertion_point(module_scope)
