# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendApplySource.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x46riendApplySource.proto*\xe2\x01\n\x11\x46riendApplySource\x12\x1c\n\x18\x46RIEND_APPLY_SOURCE_NONE\x10\x00\x12\x1e\n\x1a\x46RIEND_APPLY_SOURCE_SEARCH\x10\x01\x12!\n\x1d\x46RIEND_APPLY_SOURCE_RECOMMEND\x10\x02\x12\x1e\n\x1a\x46RIEND_APPLY_SOURCE_ASSIST\x10\x03\x12(\n$FRIEND_APPLY_SOURCE_RECOMMEND_ASSIST\x10\x04\x12\"\n\x1e\x46RIEND_APPLY_SOURCE_PSN_FRIEND\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FriendApplySource_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRIENDAPPLYSOURCE']._serialized_start=28
  _globals['_FRIENDAPPLYSOURCE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
