# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendListInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SimpleInfo_pb2 as SimpleInfo__pb2
import PlayingState_pb2 as PlayingState__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x46riendListInfo.proto\x1a\x10SimpleInfo.proto\x1a\x12PlayingState.proto\"\x80\x01\n\x0e\x46riendListInfo\x12\x11\n\tis_marked\x18\x07 \x01(\x08\x12 \n\x0bsimple_info\x18\x02 \x01(\x0b\x32\x0b.SimpleInfo\x12\x13\n\x0bremark_name\x18\r \x01(\t\x12$\n\rplaying_state\x18\t \x01(\x0e\x32\r.PlayingStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FriendListInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRIENDLISTINFO']._serialized_start=63
  _globals['_FRIENDLISTINFO']._serialized_end=191
# @@protoc_insertion_point(module_scope)
