# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendRecommendInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SimpleInfo_pb2 as SimpleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x46riendRecommendInfo.proto\x1a\x10SimpleInfo.proto\"7\n\x13\x46riendRecommendInfo\x12 \n\x0bsimple_info\x18\x03 \x01(\x0b\x32\x0b.SimpleInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FriendRecommendInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRIENDRECOMMENDINFO']._serialized_start=47
  _globals['_FRIENDRECOMMENDINFO']._serialized_end=102
# @@protoc_insertion_point(module_scope)
