# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendOnlineStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x46riendOnlineStatus.proto*W\n\x12\x46riendOnlineStatus\x12 \n\x1c\x46RIEND_ONLINE_STATUS_OFFLINE\x10\x00\x12\x1f\n\x1b\x46RIEND_ONLINE_STATUS_ONLINE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FriendOnlineStatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRIENDONLINESTATUS']._serialized_start=28
  _globals['_FRIENDONLINESTATUS']._serialized_end=115
# @@protoc_insertion_point(module_scope)
