# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GachaCeiling.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GachaCeilingAvatar_pb2 as GachaCeilingAvatar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12GachaCeiling.proto\x1a\x18GachaCeilingAvatar.proto\"a\n\x0cGachaCeiling\x12\x12\n\nis_claimed\x18\t \x01(\x08\x12(\n\x0b\x61vatar_list\x18\x05 \x03(\x0b\x32\x13.GachaCeilingAvatar\x12\x13\n\x0b\x63\x65iling_num\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GachaCeiling_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GACHACEILING']._serialized_start=48
  _globals['_GACHACEILING']._serialized_end=145
# @@protoc_insertion_point(module_scope)
