# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GachaInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GachaCeiling_pb2 as GachaCeiling__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fGachaInfo.proto\x1a\x12GachaCeiling.proto\"\xb5\x01\n\tGachaInfo\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x12\x12\n\nbegin_time\x18\x05 \x01(\x03\x12\x0f\n\x07up_info\x18\n \x03(\r\x12\x10\n\x08\x66\x65\x61tured\x18\x04 \x03(\r\x12\x13\n\x0bhistory_url\x18\x07 \x01(\t\x12\x12\n\ndetail_url\x18\x02 \x01(\t\x12$\n\rgacha_ceiling\x18\x01 \x01(\x0b\x32\r.GachaCeiling\x12\x10\n\x08gacha_id\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GachaInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GACHAINFO']._serialized_start=40
  _globals['_GACHAINFO']._serialized_end=221
# @@protoc_insertion_point(module_scope)
