# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Gateserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Gateserver.proto\"\xd4\x02\n\nGateserver\x12\x0f\n\x07lua_url\x18\x03 \x01(\t\x12\x17\n\x0f\x65x_resource_url\x18\x05 \x01(\t\x12\x18\n\x10\x61sset_bundle_url\x18\x07 \x01(\t\x12\x11\n\x08ifix_url\x18\x90\r \x01(\t\x12\x13\n\x0bregion_name\x18\n \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x0b \x01(\r\x12\x0c\n\x03msg\x18\xe0\x0f \x01(\t\x12\x15\n\x0cifix_version\x18\xba\x04 \x01(\t\x12\x18\n\x0fmdk_res_version\x18\xc3\x05 \x01(\t\x12\x1a\n\x11\x63lient_secret_key\x18\xe6\x06 \x01(\t\x12\x0c\n\x04unk1\x18\t \x01(\x08\x12\x0c\n\x04unk2\x18\x0c \x01(\x08\x12\r\n\x04unk3\x18\xfc\x07 \x01(\x08\x12\r\n\x04unk4\x18\xc9\n \x01(\x08\x12\r\n\x04unk5\x18\x99\x0b \x01(\x08\x12\r\n\x04unk6\x18\xcb\r \x01(\x08\x12\r\n\x04unk7\x18\xa2\x0e \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Gateserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GATESERVER']._serialized_start=21
  _globals['_GATESERVER']._serialized_end=361
# @@protoc_insertion_point(module_scope)
