# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetArchiveDataScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ArchiveData_pb2 as ArchiveData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19GetArchiveDataScRsp.proto\x1a\x11\x41rchiveData.proto\"J\n\x13GetArchiveDataScRsp\x12\"\n\x0c\x61rchive_data\x18\t \x01(\x0b\x32\x0c.ArchiveData\x12\x0f\n\x07retcode\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetArchiveDataScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETARCHIVEDATASCRSP']._serialized_start=48
  _globals['_GETARCHIVEDATASCRSP']._serialized_end=122
# @@protoc_insertion_point(module_scope)
