# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetAvatarDataScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Avatar_pb2 as Avatar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18GetAvatarDataScRsp.proto\x1a\x0c\x41vatar.proto\"W\n\x12GetAvatarDataScRsp\x12\x0f\n\x07retcode\x18\x07 \x01(\r\x12\x12\n\nis_get_all\x18\x03 \x01(\x08\x12\x1c\n\x0b\x61vatar_list\x18\t \x03(\x0b\x32\x07.Avatarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetAvatarDataScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETAVATARDATASCRSP']._serialized_start=42
  _globals['_GETAVATARDATASCRSP']._serialized_end=129
# @@protoc_insertion_point(module_scope)
