# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetBasicInfoScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PlayerSettingInfo_pb2 as PlayerSettingInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GetBasicInfoScRsp.proto\x1a\x17PlayerSettingInfo.proto\"\xf8\x01\n\x11GetBasicInfoScRsp\x12\x0f\n\x07\x63ur_day\x18\x0f \x01(\r\x12\x1e\n\x16last_set_nickname_time\x18\x0e \x01(\x03\x12\x16\n\x0e\x65xchange_times\x18\x02 \x01(\r\x12\"\n\x1aweek_cocoon_finished_count\x18\x01 \x01(\r\x12/\n\x13player_setting_info\x18\x0b \x01(\x0b\x32\x12.PlayerSettingInfo\x12\x19\n\x11gameplay_birthday\x18\r \x01(\r\x12\x19\n\x11next_recover_time\x18\x04 \x01(\x03\x12\x0f\n\x07retcode\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetBasicInfoScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETBASICINFOSCRSP']._serialized_start=53
  _globals['_GETBASICINFOSCRSP']._serialized_end=301
# @@protoc_insertion_point(module_scope)
