# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetCurSceneInfoScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneInfo_pb2 as SceneInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGetCurSceneInfoScRsp.proto\x1a\x0fSceneInfo.proto\"B\n\x14GetCurSceneInfoScRsp\x12\x0f\n\x07retcode\x18\x0e \x01(\r\x12\x19\n\x05scene\x18\x0c \x01(\x0b\x32\n.SceneInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetCurSceneInfoScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETCURSCENEINFOSCRSP']._serialized_start=47
  _globals['_GETCURSCENEINFOSCRSP']._serialized_end=113
# @@protoc_insertion_point(module_scope)
