# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetChallengeScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Challenge_pb2 as Challenge__pb2
import ChallengeReward_pb2 as ChallengeReward__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GetChallengeScRsp.proto\x1a\x0f\x43hallenge.proto\x1a\x15\x43hallengeReward.proto\"y\n\x11GetChallengeScRsp\x12\"\n\x0e\x63hallenge_list\x18\x02 \x03(\x0b\x32\n.Challenge\x12\x0f\n\x07retcode\x18\t \x01(\r\x12/\n\x15\x63hallenge_reward_list\x18\x07 \x03(\x0b\x32\x10.ChallengeRewardb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetChallengeScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETCHALLENGESCRSP']._serialized_start=67
  _globals['_GETCHALLENGESCRSP']._serialized_end=188
# @@protoc_insertion_point(module_scope)
