# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetEnteredSceneScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EnteredSceneInfo_pb2 as EnteredSceneInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGetEnteredSceneScRsp.proto\x1a\x16\x45nteredSceneInfo.proto\"V\n\x14GetEnteredSceneScRsp\x12-\n\x12\x65ntered_scene_info\x18\x0f \x03(\x0b\x32\x11.EnteredSceneInfo\x12\x0f\n\x07retcode\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetEnteredSceneScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETENTEREDSCENESCRSP']._serialized_start=54
  _globals['_GETENTEREDSCENESCRSP']._serialized_end=140
# @@protoc_insertion_point(module_scope)
