# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetFirstTalkByPerformanceNpcScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import NpcTalkInfo_pb2 as NpcTalkInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'GetFirstTalkByPerformanceNpcScRsp.proto\x1a\x11NpcTalkInfo.proto\"^\n!GetFirstTalkByPerformanceNpcScRsp\x12\x0f\n\x07retcode\x18\x08 \x01(\r\x12(\n\x12npc_talk_info_list\x18\n \x03(\x0b\x32\x0c.NpcTalkInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetFirstTalkByPerformanceNpcScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETFIRSTTALKBYPERFORMANCENPCSCRSP']._serialized_start=62
  _globals['_GETFIRSTTALKBYPERFORMANCENPCSCRSP']._serialized_end=156
# @@protoc_insertion_point(module_scope)
