# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetFriendRecommendListInfoScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendRecommendInfo_pb2 as FriendRecommendInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%GetFriendRecommendListInfoScRsp.proto\x1a\x19\x46riendRecommendInfo.proto\"g\n\x1fGetFriendRecommendListInfoScRsp\x12\x33\n\x15\x66riend_recommend_list\x18\x0f \x03(\x0b\x32\x14.FriendRecommendInfo\x12\x0f\n\x07retcode\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetFriendRecommendListInfoScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETFRIENDRECOMMENDLISTINFOSCRSP']._serialized_start=68
  _globals['_GETFRIENDRECOMMENDLISTINFOSCRSP']._serialized_end=171
# @@protoc_insertion_point(module_scope)
