# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetFirstTalkNpcScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FirstNpcTalkInfo_pb2 as FirstNpcTalkInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGetFirstTalkNpcScRsp.proto\x1a\x16\x46irstNpcTalkInfo.proto\"V\n\x14GetFirstTalkNpcScRsp\x12-\n\x12npc_talk_info_list\x18\x0f \x03(\x0b\x32\x11.FirstNpcTalkInfo\x12\x0f\n\x07retcode\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetFirstTalkNpcScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETFIRSTTALKNPCSCRSP']._serialized_start=54
  _globals['_GETFIRSTTALKNPCSCRSP']._serialized_end=140
# @@protoc_insertion_point(module_scope)
