# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetFriendListInfoScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendListInfo_pb2 as FriendListInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGetFriendListInfoScRsp.proto\x1a\x14\x46riendListInfo.proto\"O\n\x16GetFriendListInfoScRsp\x12\x0f\n\x07retcode\x18\r \x01(\r\x12$\n\x0b\x66riend_list\x18\x04 \x03(\x0b\x32\x0f.FriendListInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetFriendListInfoScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETFRIENDLISTINFOSCRSP']._serialized_start=54
  _globals['_GETFRIENDLISTINFOSCRSP']._serialized_end=133
# @@protoc_insertion_point(module_scope)
