# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetFriendApplyListInfoScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendApplyInfo_pb2 as FriendApplyInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!GetFriendApplyListInfoScRsp.proto\x1a\x15\x46riendApplyInfo.proto\"[\n\x1bGetFriendApplyListInfoScRsp\x12\x0f\n\x07retcode\x18\r \x01(\r\x12+\n\x11\x66riend_apply_list\x18\x0f \x03(\x0b\x32\x10.FriendApplyInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetFriendApplyListInfoScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETFRIENDAPPLYLISTINFOSCRSP']._serialized_start=60
  _globals['_GETFRIENDAPPLYLISTINFOSCRSP']._serialized_end=151
# @@protoc_insertion_point(module_scope)
