# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetFirstTalkByPerformanceNpcCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'GetFirstTalkByPerformanceNpcCsReq.proto\":\n!GetFirstTalkByPerformanceNpcCsReq\x12\x15\n\rnpc_talk_list\x18\x0e \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetFirstTalkByPerformanceNpcCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETFIRSTTALKBYPERFORMANCENPCCSREQ']._serialized_start=43
  _globals['_GETFIRSTTALKBYPERFORMANCENPCCSREQ']._serialized_end=101
# @@protoc_insertion_point(module_scope)
