# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetGachaInfoScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GachaInfo_pb2 as GachaInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GetGachaInfoScRsp.proto\x1a\x0fGachaInfo.proto\"_\n\x11GetGachaInfoScRsp\x12\x0f\n\x07retcode\x18\x04 \x01(\r\x12#\n\x0fgacha_info_list\x18\x02 \x03(\x0b\x32\n.GachaInfo\x12\x14\n\x0cgacha_random\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetGachaInfoScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETGACHAINFOSCRSP']._serialized_start=44
  _globals['_GETGACHAINFOSCRSP']._serialized_end=139
# @@protoc_insertion_point(module_scope)
