# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetJukeboxDataScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UnlockedMusic_pb2 as UnlockedMusic__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19GetJukeboxDataScRsp.proto\x1a\x13UnlockedMusic.proto\"^\n\x13GetJukeboxDataScRsp\x12\x0f\n\x07retcode\x18\x04 \x01(\r\x12\x12\n\nplaying_id\x18\x0c \x01(\r\x12\"\n\nmusic_list\x18\x02 \x03(\x0b\x32\x0e.UnlockedMusicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetJukeboxDataScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETJUKEBOXDATASCRSP']._serialized_start=50
  _globals['_GETJUKEBOXDATASCRSP']._serialized_end=144
# @@protoc_insertion_point(module_scope)
