# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetMailScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ClientMail_pb2 as ClientMail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12GetMailScRsp.proto\x1a\x10\x43lientMail.proto\"\x98\x01\n\x0cGetMailScRsp\x12\x11\n\ttotal_num\x18\x0e \x01(\r\x12\r\n\x05start\x18\r \x01(\r\x12\x0f\n\x07retcode\x18\x03 \x01(\r\x12\x1e\n\tmail_list\x18\x02 \x03(\x0b\x32\x0b.ClientMail\x12\x0e\n\x06is_end\x18\x01 \x01(\x08\x12%\n\x10notice_mail_list\x18\x05 \x03(\x0b\x32\x0b.ClientMailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetMailScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETMAILSCRSP']._serialized_start=41
  _globals['_GETMAILSCRSP']._serialized_end=193
# @@protoc_insertion_point(module_scope)
