# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetPrivateChatHistoryScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Chat_pb2 as Chat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n GetPrivateChatHistoryScRsp.proto\x1a\nChat.proto\"k\n\x1aGetPrivateChatHistoryScRsp\x12\x12\n\nsender_uid\x18\x07 \x01(\r\x12\x0e\n\x06to_uid\x18\t \x01(\r\x12\x0f\n\x07retcode\x18\x06 \x01(\r\x12\x18\n\tchat_list\x18\n \x03(\x0b\x32\x05.Chatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetPrivateChatHistoryScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETPRIVATECHATHISTORYSCRSP']._serialized_start=48
  _globals['_GETPRIVATECHATHISTORYSCRSP']._serialized_end=155
# @@protoc_insertion_point(module_scope)
