# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetQuestDataScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Quest_pb2 as Quest__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GetQuestDataScRsp.proto\x1a\x0bQuest.proto\"_\n\x11GetQuestDataScRsp\x12\x0f\n\x07retcode\x18\x08 \x01(\r\x12\x1d\n\x15total_achievement_exp\x18\n \x01(\r\x12\x1a\n\nquest_list\x18\x02 \x03(\x0b\x32\x06.Questb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetQuestDataScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETQUESTDATASCRSP']._serialized_start=40
  _globals['_GETQUESTDATASCRSP']._serialized_end=135
# @@protoc_insertion_point(module_scope)
