# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetRogueHandbookDataScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueHandbookData_pb2 as RogueHandbookData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fGetRogueHandbookDataScRsp.proto\x1a\x17RogueHandbookData.proto\"W\n\x19GetRogueHandbookDataScRsp\x12)\n\rhandbook_info\x18\x0f \x01(\x0b\x32\x12.RogueHandbookData\x12\x0f\n\x07retcode\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetRogueHandbookDataScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETROGUEHANDBOOKDATASCRSP']._serialized_start=60
  _globals['_GETROGUEHANDBOOKDATASCRSP']._serialized_end=147
# @@protoc_insertion_point(module_scope)
