# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetRollShopInfoScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGetRollShopInfoScRsp.proto\"g\n\x14GetRollShopInfoScRsp\x12\x14\n\x0croll_shop_id\x18\x04 \x01(\r\x12\x0f\n\x07retcode\x18\r \x01(\r\x12\x13\n\x0b\x44LPBJMPECFC\x18\x05 \x03(\r\x12\x13\n\x0b\x42\x42JIJINJAFK\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetRollShopInfoScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETROLLSHOPINFOSCRSP']._serialized_start=30
  _globals['_GETROLLSHOPINFOSCRSP']._serialized_end=133
# @@protoc_insertion_point(module_scope)
