# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetRogueBuffEnhanceInfoScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuffEnhanceShopInfo_pb2 as RogueBuffEnhanceShopInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"GetRogueBuffEnhanceInfoScRsp.proto\x1a\x1eRogueBuffEnhanceShopInfo.proto\"]\n\x1cGetRogueBuffEnhanceInfoScRsp\x12\x0f\n\x07retcode\x18\x0e \x01(\r\x12,\n\tshop_info\x18\x01 \x01(\x0b\x32\x19.RogueBuffEnhanceShopInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetRogueBuffEnhanceInfoScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETROGUEBUFFENHANCEINFOSCRSP']._serialized_start=70
  _globals['_GETROGUEBUFFENHANCEINFOSCRSP']._serialized_end=163
# @@protoc_insertion_point(module_scope)
