# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetRogueInitialScoreScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueScoreRewardInfo_pb2 as RogueScoreRewardInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fGetRogueInitialScoreScRsp.proto\x1a\x1aRogueScoreRewardInfo.proto\"]\n\x19GetRogueInitialScoreScRsp\x12/\n\x10rogue_score_info\x18\x04 \x01(\x0b\x32\x15.RogueScoreRewardInfo\x12\x0f\n\x07retcode\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetRogueInitialScoreScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETROGUEINITIALSCORESCRSP']._serialized_start=63
  _globals['_GETROGUEINITIALSCORESCRSP']._serialized_end=156
# @@protoc_insertion_point(module_scope)
