# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetRogueTalentInfoScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueTalentInfo_pb2 as RogueTalentInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dGetRogueTalentInfoScRsp.proto\x1a\x15RogueTalentInfo.proto\"Q\n\x17GetRogueTalentInfoScRsp\x12\x0f\n\x07retcode\x18\x04 \x01(\r\x12%\n\x0btalent_info\x18\x06 \x01(\x0b\x32\x10.RogueTalentInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetRogueTalentInfoScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETROGUETALENTINFOSCRSP']._serialized_start=56
  _globals['_GETROGUETALENTINFOSCRSP']._serialized_end=137
# @@protoc_insertion_point(module_scope)
