# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetSceneMapInfoCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGetSceneMapInfoCsReq.proto\"?\n\x14GetSceneMapInfoCsReq\x12\x10\n\x08\x65ntry_id\x18\t \x01(\r\x12\x15\n\rentry_id_list\x18\x02 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetSceneMapInfoCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETSCENEMAPINFOCSREQ']._serialized_start=30
  _globals['_GETSCENEMAPINFOCSREQ']._serialized_end=93
# @@protoc_insertion_point(module_scope)
