# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetShopListScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Shop_pb2 as Shop__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16GetShopListScRsp.proto\x1a\nShop.proto\"P\n\x10GetShopListScRsp\x12\x11\n\tshop_type\x18\x06 \x01(\r\x12\x0f\n\x07retcode\x18\x08 \x01(\r\x12\x18\n\tshop_list\x18\x07 \x03(\x0b\x32\x05.Shopb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetShopListScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETSHOPLISTSCRSP']._serialized_start=38
  _globals['_GETSHOPLISTSCRSP']._serialized_end=118
# @@protoc_insertion_point(module_scope)
