# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HandleRogueCommonPendingActionScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuffSelect_pb2 as RogueBuffSelect__pb2
import RogueRerollBuff_pb2 as RogueRerollBuff__pb2
import RogueMiracleSelect_pb2 as RogueMiracleSelect__pb2
import RogueBonusSelect_pb2 as RogueBonusSelect__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)HandleRogueCommonPendingActionScRsp.proto\x1a\x15RogueBuffSelect.proto\x1a\x15RogueRerollBuff.proto\x1a\x18RogueMiracleSelect.proto\x1a\x16RogueBonusSelect.proto\"\x83\x02\n#HandleRogueCommonPendingActionScRsp\x12\x0f\n\x07retcode\x18\x0f \x01(\r\x12\x18\n\x10\x61\x63tion_unique_id\x18\x01 \x01(\r\x12,\n\x11rogue_buff_select\x18\xb0\x05 \x01(\x0b\x32\x10.RogueBuffSelect\x12,\n\x11rogue_reroll_buff\x18\x8b\x04 \x01(\x0b\x32\x10.RogueRerollBuff\x12,\n\x0emiracle_select\x18\xe5\x05 \x01(\x0b\x32\x13.RogueMiracleSelect\x12\'\n\x0c\x62onus_select\x18; \x01(\x0b\x32\x11.RogueBonusSelectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HandleRogueCommonPendingActionScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HANDLEROGUECOMMONPENDINGACTIONSCRSP']._serialized_start=142
  _globals['_HANDLEROGUECOMMONPENDINGACTIONSCRSP']._serialized_end=401
# @@protoc_insertion_point(module_scope)
