# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HandleFriendScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendListInfo_pb2 as FriendListInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17HandleFriendScRsp.proto\x1a\x14\x46riendListInfo.proto\"u\n\x11HandleFriendScRsp\x12\x15\n\rhandle_result\x18\x02 \x01(\x08\x12\x0f\n\x07retcode\x18\x0f \x01(\r\x12\x0b\n\x03uid\x18\x05 \x01(\r\x12+\n\x12handle_friend_info\x18\n \x01(\x0b\x32\x0f.FriendListInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HandleFriendScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HANDLEFRIENDSCRSP']._serialized_start=49
  _globals['_HANDLEFRIENDSCRSP']._serialized_end=166
# @@protoc_insertion_point(module_scope)
