# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HeroBasicType.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13HeroBasicType.proto*\xfe\x01\n\rHeroBasicType\x12\x08\n\x04None\x10\x00\x12\x0f\n\nBoyWarrior\x10\xc1>\x12\x10\n\x0bGirlWarrior\x10\xc2>\x12\x0e\n\tBoyKnight\x10\xc3>\x12\x0f\n\nGirlKnight\x10\xc4>\x12\r\n\x08\x42oyRogue\x10\xc5>\x12\x0e\n\tGirlRogue\x10\xc6>\x12\x0c\n\x07\x42oyMage\x10\xc7>\x12\r\n\x08GirlMage\x10\xc8>\x12\x0e\n\tBoyShaman\x10\xc9>\x12\x0f\n\nGirlShaman\x10\xca>\x12\x0f\n\nBoyWarlock\x10\xcb>\x12\x10\n\x0bGirlWarlock\x10\xcc>\x12\x0e\n\tBoyPriest\x10\xcd>\x12\x0f\n\nGirlPriest\x10\xce>b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HeroBasicType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEROBASICTYPE']._serialized_start=24
  _globals['_HEROBASICTYPE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
