# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InteractChargerCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChargerInfo_pb2 as ChargerInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aInteractChargerCsReq.proto\x1a\x11\x43hargerInfo.proto\":\n\x14InteractChargerCsReq\x12\"\n\x0c\x63harger_info\x18\x02 \x01(\x0b\x32\x0c.ChargerInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InteractChargerCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTERACTCHARGERCSREQ']._serialized_start=49
  _globals['_INTERACTCHARGERCSREQ']._serialized_end=107
# @@protoc_insertion_point(module_scope)
