# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InteractPropScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17InteractPropScRsp.proto\"P\n\x11InteractPropScRsp\x12\x0f\n\x07retcode\x18\n \x01(\r\x12\x12\n\nprop_state\x18\x0c \x01(\r\x12\x16\n\x0eprop_entity_id\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InteractPropScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTERACTPROPSCRSP']._serialized_start=27
  _globals['_INTERACTPROPSCRSP']._serialized_end=107
# @@protoc_insertion_point(module_scope)
