# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ItemCost.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PileItem_pb2 as PileItem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eItemCost.proto\x1a\x0ePileItem.proto\"^\n\x08ItemCost\x12\x1c\n\tpile_item\x18\x06 \x01(\x0b\x32\t.PileItem\x12\x1b\n\x13\x65quipment_unique_id\x18\x07 \x01(\r\x12\x17\n\x0frelic_unique_id\x18\x0b \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ItemCost_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEMCOST']._serialized_start=34
  _globals['_ITEMCOST']._serialized_end=128
# @@protoc_insertion_point(module_scope)
