# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ItemList.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Item_pb2 as Item__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eItemList.proto\x1a\nItem.proto\"$\n\x08ItemList\x12\x18\n\titem_list\x18\x02 \x03(\x0b\x32\x05.Itemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ItemList_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEMLIST']._serialized_start=30
  _globals['_ITEMLIST']._serialized_end=66
# @@protoc_insertion_point(module_scope)
