# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LLJFPKKLGAK.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LANBPBBAJLM_pb2 as LANBPBBAJLM__pb2
import RogueSyncContextBoardEvent_pb2 as RogueSyncContextBoardEvent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11LLJFPKKLGAK.proto\x1a\x11LANBPBBAJLM.proto\x1a RogueSyncContextBoardEvent.proto\"b\n\x0bLLJFPKKLGAK\x12!\n\x0bOLMCGHBDKIE\x18\x01 \x01(\x0b\x32\x0c.LANBPBBAJLM\x12\x30\n\x0bPJALJFEJGDD\x18\t \x01(\x0b\x32\x1b.RogueSyncContextBoardEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LLJFPKKLGAK_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LLJFPKKLGAK']._serialized_start=74
  _globals['_LLJFPKKLGAK']._serialized_end=172
# @@protoc_insertion_point(module_scope)
