# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LockEquipmentCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18LockEquipmentCsReq.proto\"E\n\x12LockEquipmentCsReq\x12\x14\n\x0cis_protected\x18\x06 \x01(\x08\x12\x19\n\x11\x65quipment_id_list\x18\x03 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LockEquipmentCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCKEQUIPMENTCSREQ']._serialized_start=28
  _globals['_LOCKEQUIPMENTCSREQ']._serialized_end=97
# @@protoc_insertion_point(module_scope)
