# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MapInfoChestType.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16MapInfoChestType.proto*\x93\x01\n\x10MapInfoChestType\x12\x1c\n\x18MAP_INFO_CHEST_TYPE_NONE\x10\x00\x12\x1e\n\x1aMAP_INFO_CHEST_TYPE_NORMAL\x10\x65\x12!\n\x1dMAP_INFO_CHEST_TYPE_CHALLENGE\x10\x66\x12\x1e\n\x1aMAP_INFO_CHEST_TYPE_PUZZLE\x10hb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MapInfoChestType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPINFOCHESTTYPE']._serialized_start=27
  _globals['_MAPINFOCHESTTYPE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
