# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MazeChest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MapInfoChestType_pb2 as MapInfoChestType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fMazeChest.proto\x1a\x16MapInfoChestType.proto\"t\n\tMazeChest\x12.\n\x13map_info_chest_type\x18\x08 \x01(\x0e\x32\x11.MapInfoChestType\x12\x19\n\x11total_amount_list\x18\x07 \x01(\r\x12\x1c\n\x14unlocked_amount_list\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MazeChest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAZECHEST']._serialized_start=43
  _globals['_MAZECHEST']._serialized_end=159
# @@protoc_insertion_point(module_scope)
