# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MissionSync.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Mission_pb2 as Mission__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11MissionSync.proto\x1a\rMission.proto\"p\n\x0bMissionSync\x12\x13\n\x0b\x43OLOAGDIBCC\x18\x07 \x03(\r\x12\x17\n\x0fmain_mission_id\x18\x04 \x03(\r\x12\x1e\n\x0cmission_list\x18\x0b \x03(\x0b\x32\x08.Mission\x12\x13\n\x0bLMHJAPFMKDI\x18\n \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MissionSync_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MISSIONSYNC']._serialized_start=36
  _globals['_MISSIONSYNC']._serialized_end=148
# @@protoc_insertion_point(module_scope)
