# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Mission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MissionStatus_pb2 as MissionStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rMission.proto\x1a\x13MissionStatus.proto\"G\n\x07Mission\x12\x10\n\x08progress\x18\x0b \x01(\r\x12\n\n\x02id\x18\x05 \x01(\r\x12\x1e\n\x06status\x18\x06 \x01(\x0e\x32\x0e.MissionStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Mission_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MISSION']._serialized_start=38
  _globals['_MISSION']._serialized_end=109
# @@protoc_insertion_point(module_scope)
