# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MissionStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13MissionStatus.proto*^\n\rMissionStatus\x12\x10\n\x0cMISSION_NONE\x10\x00\x12\x11\n\rMISSION_DOING\x10\x01\x12\x12\n\x0eMISSION_FINISH\x10\x02\x12\x14\n\x10MISSION_PREPARED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MissionStatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MISSIONSTATUS']._serialized_start=23
  _globals['_MISSIONSTATUS']._serialized_end=117
# @@protoc_insertion_point(module_scope)
