# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgType.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rMsgType.proto*J\n\x07MsgType\x12\x11\n\rMSG_TYPE_NONE\x10\x00\x12\x18\n\x14MSG_TYPE_CUSTOM_TEXT\x10\x01\x12\x12\n\x0eMSG_TYPE_EMOJI\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MsgType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MSGTYPE']._serialized_start=17
  _globals['_MSGTYPE']._serialized_end=91
# @@protoc_insertion_point(module_scope)
