# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NpcExtraInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import NpcRogueInfo_pb2 as NpcRogueInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12NpcExtraInfo.proto\x1a\x12NpcRogueInfo.proto\"1\n\x0cNpcExtraInfo\x12!\n\nrogue_info\x18\t \x01(\x0b\x32\r.NpcRogueInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NpcExtraInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NPCEXTRAINFO']._serialized_start=42
  _globals['_NPCEXTRAINFO']._serialized_end=91
# @@protoc_insertion_point(module_scope)
