# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NpcRogueInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12NpcRogueInfo.proto\"\x82\x01\n\x0cNpcRogueInfo\x12\x14\n\x0crogue_npc_id\x18\x08 \x01(\r\x12\x17\n\x0f\x66inish_dialogue\x18\n \x01(\x08\x12\x13\n\x0b\x41\x41HKFINCBIL\x18\x07 \x01(\x08\x12\x13\n\x0bLCKILOCIFJH\x18\x0f \x01(\x08\x12\x19\n\x11\x64ialogue_group_id\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NpcRogueInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NPCROGUEINFO']._serialized_start=23
  _globals['_NPCROGUEINFO']._serialized_end=153
# @@protoc_insertion_point(module_scope)
