# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlatformType.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PlatformType.proto*\xae\x02\n\x0cPlatformType\x12\n\n\x06\x45\x44ITOR\x10\x00\x12\x07\n\x03IOS\x10\x01\x12\x0b\n\x07\x41NDROID\x10\x02\x12\x06\n\x02PC\x10\x03\x12\x07\n\x03WEB\x10\x04\x12\x07\n\x03WAP\x10\x05\x12\x07\n\x03PS4\x10\x06\x12\x0c\n\x08NINTENDO\x10\x07\x12\x11\n\rCLOUD_ANDROID\x10\x08\x12\x0c\n\x08\x43LOUD_PC\x10\t\x12\r\n\tCLOUD_IOS\x10\n\x12\x07\n\x03PS5\x10\x0b\x12\x07\n\x03MAC\x10\x0c\x12\r\n\tCLOUD_MAC\x10\r\x12\x15\n\x11\x43LOUD_WEB_ANDROID\x10\x14\x12\x11\n\rCLOUD_WEB_IOS\x10\x15\x12\x10\n\x0c\x43LOUD_WEB_PC\x10\x16\x12\x11\n\rCLOUD_WEB_MAC\x10\x17\x12\x13\n\x0f\x43LOUD_WEB_TOUCH\x10\x18\x12\x16\n\x12\x43LOUD_WEB_KEYBOARD\x10\x19\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlatformType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLATFORMTYPE']._serialized_start=23
  _globals['_PLATFORMTYPE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
