# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerSyncScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Relic_pb2 as Relic__pb2
import Equipment_pb2 as Equipment__pb2
import PlayerBasicInfo_pb2 as PlayerBasicInfo__pb2
import BoardDataSync_pb2 as BoardDataSync__pb2
import Material_pb2 as Material__pb2
import AvatarSync_pb2 as AvatarSync__pb2
import MissionSync_pb2 as MissionSync__pb2
import HeroBasicTypeInfo_pb2 as HeroBasicTypeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18PlayerSyncScNotify.proto\x1a\x0bRelic.proto\x1a\x0f\x45quipment.proto\x1a\x15PlayerBasicInfo.proto\x1a\x13\x42oardDataSync.proto\x1a\x0eMaterial.proto\x1a\x10\x41vatarSync.proto\x1a\x11MissionSync.proto\x1a\x17HeroBasicTypeInfo.proto\"\x92\x03\n\x12PlayerSyncScNotify\x12\"\n\x0e\x65quipment_list\x18\x03 \x03(\x0b\x32\n.Equipment\x12\x1e\n\x15total_achievement_exp\x18\xbd\r \x01(\r\x12\"\n\x0cmission_sync\x18\t \x01(\x0b\x32\x0c.MissionSync\x12 \n\x0b\x61vatar_sync\x18\x05 \x01(\x0b\x32\x0b.AvatarSync\x12(\n\x0f\x62oard_data_sync\x18\x81\r \x01(\x0b\x32\x0e.BoardDataSync\x12\x1a\n\nrelic_list\x18\x06 \x03(\x0b\x32\x06.Relic\x12 \n\rmaterial_list\x18\x0e \x03(\x0b\x32\t.Material\x12$\n\nbasic_info\x18\x04 \x01(\x0b\x32\x10.PlayerBasicInfo\x12\x30\n\x14\x62\x61sic_type_info_list\x18\x02 \x03(\x0b\x32\x12.HeroBasicTypeInfo\x12\x16\n\x0e\x64\x65l_relic_list\x18\r \x03(\r\x12\x1a\n\x12\x64\x65l_equipment_list\x18\x01 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerSyncScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERSYNCSCNOTIFY']._serialized_start=181
  _globals['_PLAYERSYNCSCNOTIFY']._serialized_end=583
# @@protoc_insertion_point(module_scope)
