# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerBasicInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15PlayerBasicInfo.proto\"\x92\x01\n\x0fPlayerBasicInfo\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\r\x12\x0b\n\x03\x65xp\x18\x03 \x01(\r\x12\x0f\n\x07stamina\x18\x04 \x01(\r\x12\r\n\x05mcoin\x18\x05 \x01(\r\x12\r\n\x05hcoin\x18\x06 \x01(\r\x12\r\n\x05scoin\x18\x07 \x01(\r\x12\x13\n\x0bworld_level\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerBasicInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERBASICINFO']._serialized_start=26
  _globals['_PLAYERBASICINFO']._serialized_end=172
# @@protoc_insertion_point(module_scope)
