# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerDetailInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PlatformType_pb2 as PlatformType__pb2
import PlayerRecordInfo_pb2 as PlayerRecordInfo__pb2
import PlayerDisplaySettings_pb2 as PlayerDisplaySettings__pb2
import DisplayAvatarDetailInfo_pb2 as DisplayAvatarDetailInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16PlayerDetailInfo.proto\x1a\x12PlatformType.proto\x1a\x16PlayerRecordInfo.proto\x1a\x1bPlayerDisplaySettings.proto\x1a\x1d\x44isplayAvatarDetailInfo.proto\"\x88\x03\n\x10PlayerDetailInfo\x12\x13\n\x0bworld_level\x18\x05 \x01(\r\x12\x11\n\tsignature\x18\x02 \x01(\t\x12$\n\rplatform_type\x18\t \x01(\x0e\x32\r.PlatformType\x12\r\n\x05level\x18\x0b \x01(\r\x12\x11\n\thead_icon\x18\x0c \x01(\r\x12\x0b\n\x03uid\x18\x03 \x01(\r\x12\x10\n\x08nickname\x18\x0f \x01(\t\x12\x1c\n\x14show_display_avatars\x18\x08 \x01(\x08\x12&\n\x0brecord_info\x18\x0e \x01(\x0b\x32\x11.PlayerRecordInfo\x12\x31\n\x10\x64isplay_settings\x18\xac\x0f \x01(\x0b\x32\x16.PlayerDisplaySettings\x12\x35\n\x13\x64isplay_avatar_list\x18\x07 \x03(\x0b\x32\x18.DisplayAvatarDetailInfo\x12\x35\n\x12\x61ssist_avatar_list\x18\xf5\x02 \x03(\x0b\x32\x18.DisplayAvatarDetailInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerDetailInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERDETAILINFO']._serialized_start=131
  _globals['_PLAYERDETAILINFO']._serialized_end=523
# @@protoc_insertion_point(module_scope)
