# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerLoginScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PlayerBasicInfo_pb2 as PlayerBasicInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16PlayerLoginScRsp.proto\x1a\x15PlayerBasicInfo.proto\"\xa3\x01\n\x10PlayerLoginScRsp\x12\x0f\n\x07stamina\x18\x01 \x01(\r\x12\x14\n\x0clogin_random\x18\x0f \x01(\x04\x12\x14\n\x0c\x63ur_timezone\x18\x0c \x01(\x11\x12\x0f\n\x07retcode\x18\x02 \x01(\r\x12$\n\nbasic_info\x18\t \x01(\x0b\x32\x10.PlayerBasicInfo\x12\x1b\n\x13server_timestamp_ms\x18\x07 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerLoginScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERLOGINSCRSP']._serialized_start=50
  _globals['_PLAYERLOGINSCRSP']._serialized_end=213
# @@protoc_insertion_point(module_scope)
