# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerDisplaySettings.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DisplayRecordType_pb2 as DisplayRecordType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bPlayerDisplaySettings.proto\x1a\x17\x44isplayRecordType.proto\"\xa9\x01\n\x15PlayerDisplaySettings\x12\x13\n\x0b\x41MGBJCGCHLE\x18\x03 \x01(\x08\x12\'\n\x0bGLJHHOCLNFC\x18\n \x01(\x0e\x32\x12.DisplayRecordType\x12\x13\n\x0b\x41OKKOOOODCN\x18\r \x01(\x08\x12\x13\n\x0bLJEELNKPIFJ\x18\x01 \x01(\x08\x12\x13\n\x0bIDFLCNJJLDO\x18\x08 \x01(\x08\x12\x13\n\x0b\x46\x45\x45\x45LLEAEPC\x18\x0c \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerDisplaySettings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERDISPLAYSETTINGS']._serialized_start=57
  _globals['_PLAYERDISPLAYSETTINGS']._serialized_end=226
# @@protoc_insertion_point(module_scope)
