# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayingState.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PlayingState.proto*\xe7\x01\n\x0cPlayingState\x12\x16\n\x12PLAYING_STATE_NONE\x10\x00\x12\x18\n\x14PLAYING_ROGUE_COSMOS\x10\x01\x12\x17\n\x13PLAYING_ROGUE_CHESS\x10\x02\x12\x1c\n\x18PLAYING_ROGUE_CHESS_NOUS\x10\x03\x12\x1c\n\x18PLAYING_CHALLENGE_MEMORY\x10\x04\x12\x1b\n\x17PLAYING_CHALLENGE_STORY\x10\x05\x12\x1a\n\x16PLAYING_CHALLENGE_BOSS\x10\x06\x12\x17\n\x13PLAYING_ROGUE_TOURN\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayingState_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYINGSTATE']._serialized_start=23
  _globals['_PLAYINGSTATE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
