# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayBackGroundMusicScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ePlayBackGroundMusicScRsp.proto\"V\n\x18PlayBackGroundMusicScRsp\x12\x15\n\rplay_music_id\x18\x0f \x01(\r\x12\x0f\n\x07retcode\x18\t \x01(\r\x12\x12\n\nplaying_id\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayBackGroundMusicScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYBACKGROUNDMUSICSCRSP']._serialized_start=34
  _globals['_PLAYBACKGROUNDMUSICSCRSP']._serialized_end=120
# @@protoc_insertion_point(module_scope)
