# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerRecordInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PlayerCollectionInfo_pb2 as PlayerCollectionInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16PlayerRecordInfo.proto\x1a\x1aPlayerCollectionInfo.proto\"\xea\x01\n\x10PlayerRecordInfo\x12\x13\n\x0b\x44KDINDMGEJH\x18\x05 \x01(\r\x12\x13\n\x0b\x42\x46GDPMKBHNB\x18\x06 \x01(\r\x12\x13\n\x0bPNIAMOINNJF\x18\r \x01(\r\x12\x13\n\x0bLAAOICJFOPI\x18\x01 \x01(\r\x12\x13\n\x0bJJOHCDLEDMO\x18\x0b \x01(\r\x12\x13\n\x0b\x45\x45JCCFCIGDF\x18\x0c \x01(\r\x12\x13\n\x0bPDHAFOAOMPB\x18\x02 \x01(\r\x12.\n\x0f\x63ollection_info\x18\x07 \x01(\x0b\x32\x15.PlayerCollectionInfo\x12\x13\n\x0bIPOCLBEJIAF\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerRecordInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERRECORDINFO']._serialized_start=55
  _globals['_PLAYERRECORDINFO']._serialized_end=289
# @@protoc_insertion_point(module_scope)
