# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerCollectionInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aPlayerCollectionInfo.proto\"\x7f\n\x14PlayerCollectionInfo\x12\x13\n\x0b\x41PBMGEBOHPK\x18\n \x01(\r\x12\x13\n\x0bOPKIPBKCHHK\x18\x06 \x01(\r\x12\x13\n\x0bJBADNDDCGFK\x18\x0f \x01(\r\x12\x13\n\x0b\x46OLOHMFJFLM\x18\x0c \x01(\r\x12\x13\n\x0bHFMNHPOGANN\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerCollectionInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERCOLLECTIONINFO']._serialized_start=30
  _globals['_PLAYERCOLLECTIONINFO']._serialized_end=157
# @@protoc_insertion_point(module_scope)
