# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerSettingInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DisplayRecordType_pb2 as DisplayRecordType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17PlayerSettingInfo.proto\x1a\x17\x44isplayRecordType.proto\"\x8c\x01\n\x11PlayerSettingInfo\x12\n\n\x02\x62\x31\x18\x02 \x01(\x08\x12\n\n\x02\x62\x32\x18\x08 \x01(\x08\x12\n\n\x02\x62\x33\x18\x04 \x01(\x08\x12\n\n\x02\x62\x34\x18\x03 \x01(\x08\x12\n\n\x02\x62\x35\x18\r \x01(\x08\x12\n\n\x02\x62\x36\x18\x05 \x01(\x08\x12/\n\x13\x64isplay_record_type\x18\x0c \x01(\x0e\x32\x12.DisplayRecordTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerSettingInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERSETTINGINFO']._serialized_start=53
  _globals['_PLAYERSETTINGINFO']._serialized_end=193
# @@protoc_insertion_point(module_scope)
