# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PromoteAvatarCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemCost_pb2 as ItemCost__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18PromoteAvatarCsReq.proto\x1a\x0eItemCost.proto\"J\n\x12PromoteAvatarCsReq\x12\x16\n\x0e\x62\x61se_avatar_id\x18\t \x01(\r\x12\x1c\n\titem_list\x18\x07 \x03(\x0b\x32\t.ItemCostb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PromoteAvatarCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROMOTEAVATARCSREQ']._serialized_start=44
  _globals['_PROMOTEAVATARCSREQ']._serialized_end=118
# @@protoc_insertion_point(module_scope)
