# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PropExtraInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PropRogueInfo_pb2 as PropRogueInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13PropExtraInfo.proto\x1a\x13PropRogueInfo.proto\"=\n\rPropExtraInfo\x12$\n\nrogue_info\x18\x0e \x01(\x0b\x32\x0e.PropRogueInfoH\x00\x42\x06\n\x04infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PropExtraInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROPEXTRAINFO']._serialized_start=44
  _globals['_PROPEXTRAINFO']._serialized_end=105
# @@protoc_insertion_point(module_scope)
