# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PVEBattleResultCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BattleEndStatus_pb2 as BattleEndStatus__pb2
import BattleOp_pb2 as BattleOp__pb2
import BattleStatistics_pb2 as BattleStatistics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aPVEBattleResultCsReq.proto\x1a\x15\x42\x61ttleEndStatus.proto\x1a\x0e\x42\x61ttleOp.proto\x1a\x16\x42\x61ttleStatistics.proto\"\x8c\x02\n\x14PVEBattleResultCsReq\x12\x11\n\tbattle_id\x18\x0b \x01(\r\x12\x1a\n\x12\x63lient_res_version\x18\x05 \x01(\r\x12\x10\n\x08stage_id\x18\x08 \x01(\r\x12$\n\nend_status\x18\x0f \x01(\x0e\x32\x10.BattleEndStatus\x12\x11\n\tcost_time\x18\r \x01(\r\x12\x1a\n\x12turn_snapshot_hash\x18\x01 \x01(\x0c\x12\x1a\n\x07op_list\x18\x0c \x03(\x0b\x32\t.BattleOp\x12\x1e\n\x03stt\x18\x0e \x01(\x0b\x32\x11.BattleStatistics\x12\"\n\x1ais_ai_consider_ultra_skill\x18\n \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PVEBattleResultCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PVEBATTLERESULTCSREQ']._serialized_start=94
  _globals['_PVEBATTLERESULTCSREQ']._serialized_end=362
# @@protoc_insertion_point(module_scope)
