# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QuestStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11QuestStatus.proto*c\n\x0bQuestStatus\x12\x0e\n\nQUEST_NONE\x10\x00\x12\x0f\n\x0bQUEST_DOING\x10\x01\x12\x10\n\x0cQUEST_FINISH\x10\x02\x12\x0f\n\x0bQUEST_CLOSE\x10\x03\x12\x10\n\x0cQUEST_DELETE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QuestStatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUESTSTATUS']._serialized_start=21
  _globals['_QUESTSTATUS']._serialized_end=120
# @@protoc_insertion_point(module_scope)
