# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Quest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import QuestStatus_pb2 as QuestStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bQuest.proto\x1a\x11QuestStatus.proto\"X\n\x05Quest\x12\x13\n\x0b\x66inish_time\x18\x03 \x01(\x03\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08progress\x18\t \x01(\r\x12\x1c\n\x06status\x18\r \x01(\x0e\x32\x0c.QuestStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Quest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUEST']._serialized_start=34
  _globals['_QUEST']._serialized_end=122
# @@protoc_insertion_point(module_scope)
