# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QuitLineupCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ExtraLineupType_pb2 as ExtraLineupType__pb2
import AvatarType_pb2 as AvatarType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15QuitLineupCsReq.proto\x1a\x15\x45xtraLineupType.proto\x1a\x10\x41vatarType.proto\"\xad\x01\n\x0fQuitLineupCsReq\x12+\n\x11\x65xtra_lineup_type\x18\x07 \x01(\x0e\x32\x10.ExtraLineupType\x12\r\n\x05index\x18\n \x01(\r\x12 \n\x0b\x61vatar_type\x18\x06 \x01(\x0e\x32\x0b.AvatarType\x12\x12\n\nis_virtual\x18\x0e \x01(\x08\x12\x10\n\x08plane_id\x18\x0f \x01(\r\x12\x16\n\x0e\x62\x61se_avatar_id\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QuitLineupCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUITLINEUPCSREQ']._serialized_start=67
  _globals['_QUITLINEUPCSREQ']._serialized_end=240
# @@protoc_insertion_point(module_scope)
