# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RankUpEquipmentCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemCostList_pb2 as ItemCostList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aRankUpEquipmentCsReq.proto\x1a\x12ItemCostList.proto\"Z\n\x14RankUpEquipmentCsReq\x12%\n\x0eitem_cost_list\x18\t \x01(\x0b\x32\r.ItemCostList\x12\x1b\n\x13\x65quipment_unique_id\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RankUpEquipmentCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RANKUPEQUIPMENTCSREQ']._serialized_start=50
  _globals['_RANKUPEQUIPMENTCSREQ']._serialized_end=140
# @@protoc_insertion_point(module_scope)
