# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReEnterLastElementStageScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneBattleInfo_pb2 as SceneBattleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ReEnterLastElementStageScRsp.proto\x1a\x15SceneBattleInfo.proto\"h\n\x1cReEnterLastElementStageScRsp\x12\x10\n\x08stage_id\x18\r \x01(\r\x12\x0f\n\x07retcode\x18\x03 \x01(\r\x12%\n\x0b\x62\x61ttle_info\x18\x08 \x01(\x0b\x32\x10.SceneBattleInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReEnterLastElementStageScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REENTERLASTELEMENTSTAGESCRSP']._serialized_start=61
  _globals['_REENTERLASTELEMENTSTAGESCRSP']._serialized_end=165
# @@protoc_insertion_point(module_scope)
