# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RefreshTriggerByClientScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!RefreshTriggerByClientScRsp.proto\"x\n\x1bRefreshTriggerByClientScRsp\x12\x19\n\x11trigger_entity_id\x18\x04 \x01(\r\x12\x14\n\x0ctrigger_name\x18\x0b \x01(\t\x12\x17\n\x0frefresh_trigger\x18\x05 \x01(\x08\x12\x0f\n\x07retcode\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RefreshTriggerByClientScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REFRESHTRIGGERBYCLIENTSCRSP']._serialized_start=37
  _globals['_REFRESHTRIGGERBYCLIENTSCRSP']._serialized_end=157
# @@protoc_insertion_point(module_scope)
