# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RefreshTriggerByClientScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$RefreshTriggerByClientScNotify.proto\"q\n\x1eRefreshTriggerByClientScNotify\x12\x14\n\x0ctrigger_name\x18\t \x01(\t\x12\x1e\n\x16trigger_target_id_list\x18\x04 \x03(\r\x12\x19\n\x11trigger_entity_id\x18\r \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RefreshTriggerByClientScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REFRESHTRIGGERBYCLIENTSCNOTIFY']._serialized_start=40
  _globals['_REFRESHTRIGGERBYCLIENTSCNOTIFY']._serialized_end=153
# @@protoc_insertion_point(module_scope)
