# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Relic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RelicAffix_pb2 as RelicAffix__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bRelic.proto\x1a\x10RelicAffix.proto\"\xc4\x01\n\x05Relic\x12\r\n\x05level\x18\t \x01(\r\x12\x14\n\x0cis_protected\x18\x0b \x01(\x08\x12\x0b\n\x03\x65xp\x18\x02 \x01(\r\x12\x14\n\x0cis_discarded\x18\x05 \x01(\x08\x12\x0b\n\x03tid\x18\x06 \x01(\r\x12\x15\n\rmain_affix_id\x18\x01 \x01(\r\x12\x17\n\x0f\x65quip_avatar_id\x18\x0f \x01(\r\x12\x11\n\tunique_id\x18\x03 \x01(\r\x12#\n\x0esub_affix_list\x18\x0e \x03(\x0b\x32\x0b.RelicAffixb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Relic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RELIC']._serialized_start=34
  _globals['_RELIC']._serialized_end=230
# @@protoc_insertion_point(module_scope)
