# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemoveRotaterScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RotaterData_pb2 as RotaterData__pb2
import RotatorEnergyInfo_pb2 as RotatorEnergyInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18RemoveRotaterScRsp.proto\x1a\x11RotaterData.proto\x1a\x17RotatorEnergyInfo.proto\"r\n\x12RemoveRotaterScRsp\x12\"\n\x0crotater_data\x18\r \x01(\x0b\x32\x0c.RotaterData\x12\x0f\n\x07retcode\x18\x02 \x01(\r\x12\'\n\x0b\x65nergy_info\x18\x0f \x01(\x0b\x32\x12.RotatorEnergyInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RemoveRotaterScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REMOVEROTATERSCRSP']._serialized_start=72
  _globals['_REMOVEROTATERSCRSP']._serialized_end=186
# @@protoc_insertion_point(module_scope)
