# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReserveStaminaExchangeScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ReserveStaminaExchangeScRsp.proto\";\n\x1bReserveStaminaExchangeScRsp\x12\x0b\n\x03num\x18\x0e \x01(\r\x12\x0f\n\x07retcode\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReserveStaminaExchangeScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESERVESTAMINAEXCHANGESCRSP']._serialized_start=37
  _globals['_RESERVESTAMINAEXCHANGESCRSP']._serialized_end=96
# @@protoc_insertion_point(module_scope)
