# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueBuffEnhanceInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemCostList_pb2 as ItemCostList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aRogueBuffEnhanceInfo.proto\x1a\x12ItemCostList.proto\"a\n\x14RogueBuffEnhanceInfo\x12%\n\x0eitem_cost_list\x18\x01 \x01(\x0b\x32\r.ItemCostList\x12\x11\n\tunk_float\x18\x04 \x01(\x02\x12\x0f\n\x07\x62uff_id\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueBuffEnhanceInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEBUFFENHANCEINFO']._serialized_start=50
  _globals['_ROGUEBUFFENHANCEINFO']._serialized_end=147
# @@protoc_insertion_point(module_scope)
