# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueRoomStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RogueRoomStatus.proto*\xa1\x01\n\x0fRogueRoomStatus\x12\x1a\n\x16ROGUE_ROOM_STATUS_NONE\x10\x00\x12\x1a\n\x16ROGUE_ROOM_STATUS_LOCK\x10\x01\x12\x1c\n\x18ROGUE_ROOM_STATUS_UNLOCK\x10\x02\x12\x1a\n\x16ROGUE_ROOM_STATUS_PLAY\x10\x03\x12\x1c\n\x18ROGUE_ROOM_STATUS_FINISH\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueRoomStatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEROOMSTATUS']._serialized_start=26
  _globals['_ROGUEROOMSTATUS']._serialized_end=187
# @@protoc_insertion_point(module_scope)
