# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueSyncContextBoardEvent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n RogueSyncContextBoardEvent.proto\"R\n\x1aRogueSyncContextBoardEvent\x12\x16\n\x0e\x62oard_event_id\x18\x04 \x01(\r\x12\x1c\n\x14modifier_effect_type\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueSyncContextBoardEvent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUESYNCCONTEXTBOARDEVENT']._serialized_start=36
  _globals['_ROGUESYNCCONTEXTBOARDEVENT']._serialized_end=118
# @@protoc_insertion_point(module_scope)
