# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueCommonPendingAction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueAction_pb2 as RogueAction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eRogueCommonPendingAction.proto\x1a\x11RogueAction.proto\"Q\n\x18RogueCommonPendingAction\x12\x11\n\tunique_id\x18\x04 \x01(\r\x12\"\n\x0crogue_action\x18\x07 \x01(\x0b\x32\x0c.RogueActionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueCommonPendingAction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUECOMMONPENDINGACTION']._serialized_start=53
  _globals['_ROGUECOMMONPENDINGACTION']._serialized_end=134
# @@protoc_insertion_point(module_scope)
