# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueMiracleSource.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18RogueMiracleSource.proto*\x92\x04\n\x12RogueMiracleSource\x12\"\n\x1eROGUE_MIRACLE_SOURCE_TYPE_NONE\x10\x00\x12$\n ROGUE_MIRACLE_SOURCE_TYPE_SELECT\x10\x01\x12&\n\"ROGUE_MIRACLE_SOURCE_TYPE_DIALOGUE\x10\x02\x12#\n\x1fROGUE_MIRACLE_SOURCE_TYPE_BONUS\x10\x03\x12!\n\x1dROGUE_MIRACLE_SOURCE_TYPE_USE\x10\x04\x12#\n\x1fROGUE_MIRACLE_SOURCE_TYPE_RESET\x10\x05\x12%\n!ROGUE_MIRACLE_SOURCE_TYPE_REPLACE\x10\x06\x12#\n\x1fROGUE_MIRACLE_SOURCE_TYPE_TRADE\x10\x07\x12!\n\x1dROGUE_MIRACLE_SOURCE_TYPE_GET\x10\x08\x12\"\n\x1eROGUE_MIRACLE_SOURCE_TYPE_SHOP\x10\t\x12(\n$ROGUE_MIRACLE_SOURCE_TYPE_MAZE_SKILL\x10\n\x12-\n)ROGUE_MIRACLE_SOURCE_TYPE_LEVEL_MECHANISM\x10\x0b\x12\x31\n-ROGUE_MIRACLE_SOURCE_TYPE_ENDLESS_LEVEL_START\x10\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueMiracleSource_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEMIRACLESOURCE']._serialized_start=29
  _globals['_ROGUEMIRACLESOURCE']._serialized_end=559
# @@protoc_insertion_point(module_scope)
