# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueRecordAvatar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarType_pb2 as AvatarType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17RogueRecordAvatar.proto\x1a\x10\x41vatarType.proto\"^\n\x11RogueRecordAvatar\x12 \n\x0b\x61vatar_type\x18\x02 \x01(\x0e\x32\x0b.AvatarType\x12\r\n\x05level\x18\x01 \x01(\r\x12\x0c\n\x04slot\x18\x03 \x01(\r\x12\n\n\x02id\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueRecordAvatar_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUERECORDAVATAR']._serialized_start=45
  _globals['_ROGUERECORDAVATAR']._serialized_end=139
# @@protoc_insertion_point(module_scope)
