# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueRecordInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuff_pb2 as RogueBuff__pb2
import RogueRecordAvatar_pb2 as RogueRecordAvatar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RogueRecordInfo.proto\x1a\x0fRogueBuff.proto\x1a\x17RogueRecordAvatar.proto\"u\n\x0fRogueRecordInfo\x12\x1d\n\tbuff_list\x18\x0e \x03(\x0b\x32\n.RogueBuff\x12\x1a\n\x12rogue_miracle_list\x18\x08 \x03(\r\x12\'\n\x0b\x61vatar_list\x18\x05 \x03(\x0b\x32\x12.RogueRecordAvatarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueRecordInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUERECORDINFO']._serialized_start=67
  _globals['_ROGUERECORDINFO']._serialized_end=184
# @@protoc_insertion_point(module_scope)
