# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueCommonBuffSelectSource.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!RogueCommonBuffSelectSource.proto*\x9f\x02\n\x1bRogueCommonBuffSelectSource\x12-\n)ROGUE_COMMON_BUFF_SELECT_SOURCE_TYPE_NONE\x10\x00\x12\x32\n.ROGUE_COMMON_BUFF_SELECT_SOURCE_TYPE_DICE_ROLL\x10\x01\x12-\n)ROGUE_COMMON_BUFF_SELECT_SOURCE_TYPE_AEON\x10\x02\x12\x34\n0ROGUE_COMMON_BUFF_SELECT_SOURCE_TYPE_BOARD_EVENT\x10\x03\x12\x38\n4ROGUE_COMMON_BUFF_SELECT_SOURCE_TYPE_LEVEL_MECHANISM\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueCommonBuffSelectSource_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUECOMMONBUFFSELECTSOURCE']._serialized_start=38
  _globals['_ROGUECOMMONBUFFSELECTSOURCE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
