# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueDialogueEventParam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dRogueDialogueEventParam.proto\"x\n\x17RogueDialogueEventParam\x12\x0e\n\x06\x61rg_id\x18\x0e \x01(\r\x12\r\n\x05ratio\x18\x0c \x01(\x02\x12\x11\n\tint_value\x18\x02 \x01(\x11\x12\x10\n\x08is_valid\x18\x03 \x01(\x08\x12\x19\n\x11\x64ialogue_event_id\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueDialogueEventParam_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEDIALOGUEEVENTPARAM']._serialized_start=33
  _globals['_ROGUEDIALOGUEEVENTPARAM']._serialized_end=153
# @@protoc_insertion_point(module_scope)
