# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueHandbookAeon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17RogueHandbookAeon.proto\"\x8b\x01\n\x11RogueHandbookAeon\x12\x0b\n\x03\x65xp\x18\r \x01(\r\x12\r\n\x05level\x18\x08 \x01(\r\x12\x0f\n\x07\x61\x65on_id\x18\x0c \x01(\r\x12\x19\n\x11taken_reward_list\x18\x0f \x03(\r\x12\x11\n\tmax_level\x18\x05 \x01(\r\x12\x1b\n\x13\x61rchive_unlock_list\x18\x02 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueHandbookAeon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEHANDBOOKAEON']._serialized_start=28
  _globals['_ROGUEHANDBOOKAEON']._serialized_end=167
# @@protoc_insertion_point(module_scope)
