# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueMiracleInfoData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueMiracleDataInfo_pb2 as RogueMiracleDataInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aRogueMiracleInfoData.proto\x1a\x1aRogueMiracleDataInfo.proto\"s\n\x14RogueMiracleInfoData\x12\x13\n\x0b\x44MJLJNDFOGP\x18\x01 \x01(\r\x12\x31\n\x12rogue_miracle_list\x18\n \x03(\x0b\x32\x15.RogueMiracleDataInfo\x12\x13\n\x0bKHBDIKDDIIB\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueMiracleInfoData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEMIRACLEINFODATA']._serialized_start=58
  _globals['_ROGUEMIRACLEINFODATA']._serialized_end=173
# @@protoc_insertion_point(module_scope)
