# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueInfoData_pb2 as RogueInfoData__pb2
import RogueCurrentInfo_pb2 as RogueCurrentInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fRogueInfo.proto\x1a\x13RogueInfoData.proto\x1a\x16RogueCurrentInfo.proto\"e\n\tRogueInfo\x12.\n\x12rogue_current_info\x18\xeb\x02 \x01(\x0b\x32\x11.RogueCurrentInfo\x12(\n\x0frogue_info_data\x18\xd6\x03 \x01(\x0b\x32\x0e.RogueInfoDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEINFO']._serialized_start=64
  _globals['_ROGUEINFO']._serialized_end=165
# @@protoc_insertion_point(module_scope)
