# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueInfoData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueSeasonInfo_pb2 as RogueSeasonInfo__pb2
import RogueScoreRewardInfo_pb2 as RogueScoreRewardInfo__pb2
import RogueAeonInfo_pb2 as RogueAeonInfo__pb2
import RogueCurVirtualItemInfo_pb2 as RogueCurVirtualItemInfo__pb2
import RogueAreaInfo_pb2 as RogueAreaInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RogueInfoData.proto\x1a\x15RogueSeasonInfo.proto\x1a\x1aRogueScoreRewardInfo.proto\x1a\x13RogueAeonInfo.proto\x1a\x1dRogueCurVirtualItemInfo.proto\x1a\x13RogueAreaInfo.proto\"\xfa\x01\n\rRogueInfoData\x12+\n\x11rogue_season_info\x18\x07 \x01(\x0b\x32\x10.RogueSeasonInfo\x12/\n\x10rogue_score_info\x18\t \x01(\x0b\x32\x15.RogueScoreRewardInfo\x12\x39\n\x17rogue_virtual_item_info\x18\n \x01(\x0b\x32\x18.RogueCurVirtualItemInfo\x12\'\n\x0frogue_area_info\x18\x05 \x01(\x0b\x32\x0e.RogueAreaInfo\x12\'\n\x0frogue_aeon_info\x18\x0b \x01(\x0b\x32\x0e.RogueAeonInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueInfoData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEINFODATA']._serialized_start=148
  _globals['_ROGUEINFODATA']._serialized_end=398
# @@protoc_insertion_point(module_scope)
