# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueMiracle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12RogueMiracle.proto\"\xb5\x01\n\x0cRogueMiracle\x12\x33\n\x0bKONAGCDHKKH\x18\n \x03(\x0b\x32\x1e.RogueMiracle.KONAGCDHKKHEntry\x12\x12\n\nmiracle_id\x18\x0c \x01(\r\x12\x13\n\x0bNKBEHFHLPEF\x18\x01 \x01(\r\x12\x13\n\x0bMMFONFFPNJM\x18\x04 \x01(\r\x1a\x32\n\x10KONAGCDHKKHEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueMiracle_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _ROGUEMIRACLE_KONAGCDHKKHENTRY._options = None
  _ROGUEMIRACLE_KONAGCDHKKHENTRY._serialized_options = b'8\001'
  _globals['_ROGUEMIRACLE']._serialized_start=23
  _globals['_ROGUEMIRACLE']._serialized_end=204
  _globals['_ROGUEMIRACLE_KONAGCDHKKHENTRY']._serialized_start=154
  _globals['_ROGUEMIRACLE_KONAGCDHKKHENTRY']._serialized_end=204
# @@protoc_insertion_point(module_scope)
