# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueActionResult.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuffSource_pb2 as RogueBuffSource__pb2
import RogueActionResultData_pb2 as RogueActionResultData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17RogueActionResult.proto\x1a\x15RogueBuffSource.proto\x1a\x1bRogueActionResultData.proto\"c\n\x11RogueActionResult\x12 \n\x06source\x18\n \x01(\x0e\x32\x10.RogueBuffSource\x12,\n\x0crogue_action\x18\x05 \x01(\x0b\x32\x16.RogueActionResultDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueActionResult_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEACTIONRESULT']._serialized_start=79
  _globals['_ROGUEACTIONRESULT']._serialized_end=178
# @@protoc_insertion_point(module_scope)
