# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueAeonInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RogueAeonInfo.proto\"t\n\rRogueAeonInfo\x12\x13\n\x0bis_unlocked\x18\x06 \x01(\x08\x12\x1f\n\x17unlock_aeon_enhance_num\x18\n \x01(\r\x12\x17\n\x0funlock_aeon_num\x18\x0f \x01(\r\x12\x14\n\x0c\x61\x65on_id_list\x18\x03 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueAeonInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEAEONINFO']._serialized_start=23
  _globals['_ROGUEAEONINFO']._serialized_end=139
# @@protoc_insertion_point(module_scope)
