# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueTalentInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueTalent_pb2 as RogueTalent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RogueTalentInfo.proto\x1a\x11RogueTalent.proto\"5\n\x0fRogueTalentInfo\x12\"\n\x0crogue_talent\x18\t \x03(\x0b\x32\x0c.RogueTalentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueTalentInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUETALENTINFO']._serialized_start=44
  _globals['_ROGUETALENTINFO']._serialized_end=97
# @@protoc_insertion_point(module_scope)
