# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueCurrentInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueAeon_pb2 as RogueAeon__pb2
import RogueAvatarInfo_pb2 as RogueAvatarInfo__pb2
import RogueMiracleInfo_pb2 as RogueMiracleInfo__pb2
import RogueBuffInfo_pb2 as RogueBuffInfo__pb2
import RogueCommonPendingAction_pb2 as RogueCommonPendingAction__pb2
import RogueVirtualItemInfo_pb2 as RogueVirtualItemInfo__pb2
import RogueStatus_pb2 as RogueStatus__pb2
import RogueMapInfo_pb2 as RogueMapInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16RogueCurrentInfo.proto\x1a\x0fRogueAeon.proto\x1a\x15RogueAvatarInfo.proto\x1a\x16RogueMiracleInfo.proto\x1a\x13RogueBuffInfo.proto\x1a\x1eRogueCommonPendingAction.proto\x1a\x1aRogueVirtualItemInfo.proto\x1a\x11RogueStatus.proto\x1a\x12RogueMapInfo.proto\"\xe1\x02\n\x10RogueCurrentInfo\x12\x1f\n\x08room_map\x18\x04 \x01(\x0b\x32\r.RogueMapInfo\x12#\n\x0frogue_aeon_info\x18\x0f \x01(\x0b\x32\n.RogueAeon\x12\x1c\n\x06status\x18\r \x01(\x0e\x32\x0c.RogueStatus\x12+\n\x11rogue_avatar_info\x18\x0b \x01(\x0b\x32\x10.RogueAvatarInfo\x12\x31\n\x12rogue_virtual_item\x18\n \x01(\x0b\x32\x15.RogueVirtualItemInfo\x12\'\n\x0frogue_buff_info\x18\x05 \x01(\x0b\x32\x0e.RogueBuffInfo\x12-\n\x12rogue_miracle_info\x18\x08 \x01(\x0b\x32\x11.RogueMiracleInfo\x12\x31\n\x0epending_action\x18\x02 \x01(\x0b\x32\x19.RogueCommonPendingActionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueCurrentInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUECURRENTINFO']._serialized_start=211
  _globals['_ROGUECURRENTINFO']._serialized_end=564
# @@protoc_insertion_point(module_scope)
