# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueAreaStatus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RogueAreaStatus.proto*\x8a\x01\n\x0fRogueAreaStatus\x12\x1a\n\x16ROGUE_AREA_STATUS_LOCK\x10\x00\x12\x1c\n\x18ROGUE_AREA_STATUS_UNLOCK\x10\x01\x12 \n\x1cROGUE_AREA_STATUS_FIRST_PASS\x10\x02\x12\x1b\n\x17ROGUE_AREA_STATUS_CLOSE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueAreaStatus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEAREASTATUS']._serialized_start=26
  _globals['_ROGUEAREASTATUS']._serialized_end=164
# @@protoc_insertion_point(module_scope)
