# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueRerollBuff.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueCommonBuffSelectInfo_pb2 as RogueCommonBuffSelectInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RogueRerollBuff.proto\x1a\x1fRogueCommonBuffSelectInfo.proto\"G\n\x0fRogueRerollBuff\x12\x34\n\x10\x62uff_select_info\x18\x0f \x01(\x0b\x32\x1a.RogueCommonBuffSelectInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueRerollBuff_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEREROLLBUFF']._serialized_start=58
  _globals['_ROGUEREROLLBUFF']._serialized_end=129
# @@protoc_insertion_point(module_scope)
