# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueActionResultData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuffData_pb2 as RogueBuffData__pb2
import RogueMiracleData_pb2 as RogueMiracleData__pb2
import RogueVirtualItemData_pb2 as RogueVirtualItemData__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bRogueActionResultData.proto\x1a\x13RogueBuffData.proto\x1a\x16RogueMiracleData.proto\x1a\x1aRogueVirtualItemData.proto\"\x92\x02\n\x15RogueActionResultData\x12.\n\radd_item_list\x18\x0b \x01(\x0b\x32\x15.RogueVirtualItemDataH\x00\x12\x31\n\x10remove_item_list\x18\x0e \x01(\x0b\x32\x15.RogueVirtualItemDataH\x00\x12(\n\radd_buff_list\x18\xb2\x0c \x01(\x0b\x32\x0e.RogueBuffDataH\x00\x12+\n\x10remove_buff_list\x18\xa6\x0c \x01(\x0b\x32\x0e.RogueBuffDataH\x00\x12.\n\x10\x61\x64\x64_miracle_list\x18\x84\x04 \x01(\x0b\x32\x11.RogueMiracleDataH\x00\x42\x0f\n\rresult_actionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueActionResultData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEACTIONRESULTDATA']._serialized_start=105
  _globals['_ROGUEACTIONRESULTDATA']._serialized_end=379
# @@protoc_insertion_point(module_scope)
