# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueAreaInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueArea_pb2 as RogueArea__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RogueAreaInfo.proto\x1a\x0fRogueArea.proto\"/\n\rRogueAreaInfo\x12\x1e\n\nrogue_area\x18\x02 \x03(\x0b\x32\n.RogueAreab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueAreaInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEAREAINFO']._serialized_start=40
  _globals['_ROGUEAREAINFO']._serialized_end=87
# @@protoc_insertion_point(module_scope)
