# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueAvatarReviveCost.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemCostList_pb2 as ItemCostList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bRogueAvatarReviveCost.proto\x1a\x12ItemCostList.proto\";\n\x15RogueAvatarReviveCost\x12\"\n\x0brevive_cost\x18\x06 \x01(\x0b\x32\r.ItemCostListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueAvatarReviveCost_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEAVATARREVIVECOST']._serialized_start=51
  _globals['_ROGUEAVATARREVIVECOST']._serialized_end=110
# @@protoc_insertion_point(module_scope)
