# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueAction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueCommonBuffSelectInfo_pb2 as RogueCommonBuffSelectInfo__pb2
import RogueMiracleSelectInfo_pb2 as RogueMiracleSelectInfo__pb2
import RogueBonusSelectInfo_pb2 as RogueBonusSelectInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11RogueAction.proto\x1a\x1fRogueCommonBuffSelectInfo.proto\x1a\x1cRogueMiracleSelectInfo.proto\x1a\x1aRogueBonusSelectInfo.proto\"\xbe\x01\n\x0bRogueAction\x12\x37\n\x10\x62uff_select_info\x18\xd8\x01 \x01(\x0b\x32\x1a.RogueCommonBuffSelectInfoH\x00\x12\x37\n\x13miracle_select_info\x18\x8f\x04 \x01(\x0b\x32\x17.RogueMiracleSelectInfoH\x00\x12\x33\n\x11\x62onus_select_info\x18\x84\x03 \x01(\x0b\x32\x15.RogueBonusSelectInfoH\x00\x42\x08\n\x06\x61\x63tionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueAction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEACTION']._serialized_start=113
  _globals['_ROGUEACTION']._serialized_end=303
# @@protoc_insertion_point(module_scope)
