# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueArea.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fRogueArea.proto\"\x94\x01\n\tRogueArea\x12\x19\n\x11rogue_area_status\x18\x01 \x01(\r\x12\x14\n\x0crogue_status\x18\x08 \x01(\r\x12\x19\n\x11has_taken_rewards\x18\x0e \x01(\x08\x12\x0e\n\x06map_id\x18\x05 \x01(\r\x12\x1a\n\x12\x63ur_reach_room_num\x18\x06 \x01(\r\x12\x0f\n\x07\x61rea_id\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueArea_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEAREA']._serialized_start=20
  _globals['_ROGUEAREA']._serialized_end=168
# @@protoc_insertion_point(module_scope)
