# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueBuffSource.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15RogueBuffSource.proto*\x88\x03\n\x0fRogueBuffSource\x12\x1f\n\x1bROGUE_BUFF_SOURCE_TYPE_NONE\x10\x00\x12!\n\x1dROGUE_BUFF_SOURCE_TYPE_SELECT\x10\x01\x12\"\n\x1eROGUE_BUFF_SOURCE_TYPE_ENHANCE\x10\x02\x12\"\n\x1eROGUE_BUFF_SOURCE_TYPE_MIRACLE\x10\x03\x12#\n\x1fROGUE_BUFF_SOURCE_TYPE_DIALOGUE\x10\x04\x12 \n\x1cROGUE_BUFF_SOURCE_TYPE_BONUS\x10\x05\x12%\n!ROGUE_BUFF_SOURCE_TYPE_MAZE_SKILL\x10\x06\x12\x1f\n\x1bROGUE_BUFF_SOURCE_TYPE_SHOP\x10\x07\x12*\n&ROGUE_BUFF_SOURCE_TYPE_LEVEL_MECHANISM\x10\x08\x12.\n*ROGUE_BUFF_SOURCE_TYPE_ENDLESS_LEVEL_START\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueBuffSource_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEBUFFSOURCE']._serialized_start=26
  _globals['_ROGUEBUFFSOURCE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
