# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueHandbookData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueHandbookEvent_pb2 as RogueHandbookEvent__pb2
import RogueHandbookMiracle_pb2 as RogueHandbookMiracle__pb2
import RogueHandbookBuff_pb2 as RogueHandbookBuff__pb2
import RogueHandbookAeon_pb2 as RogueHandbookAeon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17RogueHandbookData.proto\x1a\x18RogueHandbookEvent.proto\x1a\x1aRogueHandbookMiracle.proto\x1a\x17RogueHandbookBuff.proto\x1a\x17RogueHandbookAeon.proto\"\xbe\x01\n\x11RogueHandbookData\x12(\n\x0brogue_event\x18\x0c \x03(\x0b\x32\x13.RogueHandbookEvent\x12%\n\tbuff_list\x18\n \x03(\x0b\x32\x12.RogueHandbookBuff\x12+\n\x0frogue_aeon_list\x18\t \x03(\x0b\x32\x12.RogueHandbookAeon\x12+\n\x0cmiracle_list\x18\x03 \x03(\x0b\x32\x15.RogueHandbookMiracleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueHandbookData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEHANDBOOKDATA']._serialized_start=132
  _globals['_ROGUEHANDBOOKDATA']._serialized_end=322
# @@protoc_insertion_point(module_scope)
