# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueCommonBuffSelectInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemCostList_pb2 as ItemCostList__pb2
import RogueCommonBuffSelectSource_pb2 as RogueCommonBuffSelectSource__pb2
import RogueCommonBuff_pb2 as RogueCommonBuff__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fRogueCommonBuffSelectInfo.proto\x1a\x12ItemCostList.proto\x1a!RogueCommonBuffSelectSource.proto\x1a\x15RogueCommonBuff.proto\"\xa1\x03\n\x19RogueCommonBuffSelectInfo\x12&\n\x0froll_buffs_cost\x18\x04 \x01(\x0b\x32\r.ItemCostList\x12\x1f\n\x17select_buff_source_hint\x18\x0f \x01(\r\x12\x18\n\x10source_cur_count\x18\x07 \x01(\r\x12\x1b\n\x13roll_buff_max_times\x18\x06 \x01(\r\x12\x1a\n\x12source_total_count\x18\x0c \x01(\r\x12\x10\n\x08\x63\x61n_roll\x18\x0e \x01(\x08\x12\x1c\n\x14\x66irst_buff_type_list\x18\r \x03(\r\x12\x17\n\x0froll_buff_times\x18\x03 \x01(\r\x12\x1c\n\x14roll_buff_free_count\x18\x01 \x01(\r\x12(\n\x0emaze_buff_list\x18\x05 \x03(\x0b\x32\x10.RogueCommonBuff\x12\x31\n\x0bsource_type\x18\x02 \x01(\x0e\x32\x1c.RogueCommonBuffSelectSource\x12$\n\x1chandbook_unlock_buff_id_list\x18\n \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueCommonBuffSelectInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUECOMMONBUFFSELECTINFO']._serialized_start=114
  _globals['_ROGUECOMMONBUFFSELECTINFO']._serialized_end=531
# @@protoc_insertion_point(module_scope)
