# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueDialogueEvent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueDialogueEventParam_pb2 as RogueDialogueEventParam__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18RogueDialogueEvent.proto\x1a\x1dRogueDialogueEventParam.proto\"\xc3\x01\n\x12RogueDialogueEvent\x12\x0e\n\x06npc_id\x18\x01 \x01(\r\x12\x16\n\x0egame_mode_type\x18\x06 \x01(\r\x12\x13\n\x0bMBNBIEJIBFJ\x18\r \x01(\r\x12\x19\n\x11\x64ialogue_group_id\x18\x05 \x01(\r\x12\x17\n\x0fselect_event_id\x18\x0b \x03(\r\x12<\n\x1arogue_dialogue_event_param\x18\t \x03(\x0b\x32\x18.RogueDialogueEventParamb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueDialogueEvent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEDIALOGUEEVENT']._serialized_start=60
  _globals['_ROGUEDIALOGUEEVENT']._serialized_end=255
# @@protoc_insertion_point(module_scope)
