# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueMapInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueRoom_pb2 as RogueRoom__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12RogueMapInfo.proto\x1a\x0fRogueRoom.proto\"x\n\x0cRogueMapInfo\x12\x0f\n\x07\x61rea_id\x18\x08 \x01(\r\x12\x13\n\x0b\x63ur_room_id\x18\x01 \x01(\r\x12\x1d\n\troom_list\x18\x0f \x03(\x0b\x32\n.RogueRoom\x12\x13\n\x0b\x63ur_site_id\x18\r \x01(\r\x12\x0e\n\x06map_id\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueMapInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEMAPINFO']._serialized_start=39
  _globals['_ROGUEMAPINFO']._serialized_end=159
# @@protoc_insertion_point(module_scope)
