# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueMiracleSelectInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cRogueMiracleSelectInfo.proto\"`\n\x16RogueMiracleSelectInfo\x12\x13\n\x0bJDDLGDNOIEC\x18\n \x01(\r\x12\x1b\n\x13miracle_info_remote\x18\x0c \x03(\r\x12\x14\n\x0cmiracle_info\x18\x0f \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueMiracleSelectInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEMIRACLESELECTINFO']._serialized_start=32
  _globals['_ROGUEMIRACLESELECTINFO']._serialized_end=128
# @@protoc_insertion_point(module_scope)
