# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueRoom.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueRoomStatus_pb2 as RogueRoomStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fRogueRoom.proto\x1a\x15RogueRoomStatus.proto\"T\n\tRogueRoom\x12%\n\x0broom_status\x18\x06 \x01(\x0e\x32\x10.RogueRoomStatus\x12\x0f\n\x07site_id\x18\x05 \x01(\r\x12\x0f\n\x07room_id\x18\x0f \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueRoom_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEROOM']._serialized_start=42
  _globals['_ROGUEROOM']._serialized_end=126
# @@protoc_insertion_point(module_scope)
