# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueBuffSelectInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueCommonBuffSelectSource_pb2 as RogueCommonBuffSelectSource__pb2
import ItemCostList_pb2 as ItemCostList__pb2
import RogueBuff_pb2 as RogueBuff__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19RogueBuffSelectInfo.proto\x1a!RogueCommonBuffSelectSource.proto\x1a\x12ItemCostList.proto\x1a\x0fRogueBuff.proto\"\xe6\x02\n\x13RogueBuffSelectInfo\x12&\n\x0froll_buffs_cost\x18\t \x01(\x0b\x32\r.ItemCostList\x12,\n\x06source\x18\x06 \x01(\x0e\x32\x1c.RogueCommonBuffSelectSource\x12\x10\n\x08\x63\x61n_roll\x18\r \x01(\x08\x12\x1e\n\x16select_first_buff_list\x18\x05 \x03(\r\x12\x17\n\x0froll_buff_times\x18\x07 \x01(\r\x12\x1b\n\x13roll_buff_max_times\x18\n \x01(\r\x12&\n\x1eselect_buff_source_total_count\x18\x02 \x01(\r\x12$\n\x1cselect_buff_source_cur_count\x18\x0f \x01(\r\x12\"\n\x0emaze_buff_list\x18\x0c \x03(\x0b\x32\n.RogueBuff\x12\x1f\n\x17select_buff_source_hint\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueBuffSelectInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEBUFFSELECTINFO']._serialized_start=102
  _globals['_ROGUEBUFFSELECTINFO']._serialized_end=460
# @@protoc_insertion_point(module_scope)
