# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueMiracleDataInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aRogueMiracleDataInfo.proto\"\xda\x01\n\x14RogueMiracleDataInfo\x12\x13\n\x0bODFNOGMKDOA\x18\t \x01(\r\x12;\n\x0b\x44\x46KPIBCLGOP\x18\x0e \x03(\x0b\x32&.RogueMiracleDataInfo.DFKPIBCLGOPEntry\x12\x13\n\x0bIKPLEKFLPFF\x18\x06 \x01(\r\x12\x13\n\x0bJFIPNOAJNJM\x18\x01 \x01(\r\x12\x12\n\nmiracle_id\x18\x0c \x01(\r\x1a\x32\n\x10\x44\x46KPIBCLGOPEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueMiracleDataInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _ROGUEMIRACLEDATAINFO_DFKPIBCLGOPENTRY._options = None
  _ROGUEMIRACLEDATAINFO_DFKPIBCLGOPENTRY._serialized_options = b'8\001'
  _globals['_ROGUEMIRACLEDATAINFO']._serialized_start=31
  _globals['_ROGUEMIRACLEDATAINFO']._serialized_end=249
  _globals['_ROGUEMIRACLEDATAINFO_DFKPIBCLGOPENTRY']._serialized_start=199
  _globals['_ROGUEMIRACLEDATAINFO_DFKPIBCLGOPENTRY']._serialized_end=249
# @@protoc_insertion_point(module_scope)
