# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RogueBuffEnhanceShopInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuffEnhanceInfo_pb2 as RogueBuffEnhanceInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eRogueBuffEnhanceShopInfo.proto\x1a\x1aRogueBuffEnhanceInfo.proto\"D\n\x18RogueBuffEnhanceShopInfo\x12(\n\tbuff_info\x18\x06 \x03(\x0b\x32\x15.RogueBuffEnhanceInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RogueBuffEnhanceShopInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROGUEBUFFENHANCESHOPINFO']._serialized_start=62
  _globals['_ROGUEBUFFENHANCESHOPINFO']._serialized_end=130
# @@protoc_insertion_point(module_scope)
