# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RotaterData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11RotaterData.proto\"E\n\x0bRotaterData\x12\x13\n\x0b\x41PDIFCCFAGG\x18\x01 \x01(\x02\x12\x10\n\x08group_id\x18\t \x01(\r\x12\x0f\n\x07unk_int\x18\r \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RotaterData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ROTATERDATA']._serialized_start=21
  _globals['_ROTATERDATA']._serialized_end=90
# @@protoc_insertion_point(module_scope)
