# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneCastSkillCostMpScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSceneCastSkillCostMpScRsp.proto\"G\n\x19SceneCastSkillCostMpScRsp\x12\x19\n\x11\x61ttacked_group_id\x18\x06 \x01(\r\x12\x0f\n\x07retcode\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneCastSkillCostMpScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENECASTSKILLCOSTMPSCRSP']._serialized_start=35
  _globals['_SCENECASTSKILLCOSTMPSCRSP']._serialized_end=106
# @@protoc_insertion_point(module_scope)
