# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ScenePropInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PropExtraInfo_pb2 as PropExtraInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ScenePropInfo.proto\x1a\x13PropExtraInfo.proto\"\x86\x01\n\rScenePropInfo\x12\x14\n\x0clife_time_ms\x18\x06 \x01(\r\x12\"\n\nextra_info\x18\x0f \x01(\x0b\x32\x0e.PropExtraInfo\x12\x0f\n\x07prop_id\x18\x05 \x01(\r\x12\x12\n\nprop_state\x18\x0b \x01(\r\x12\x16\n\x0e\x63reate_time_ms\x18\x01 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ScenePropInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEPROPINFO']._serialized_start=45
  _globals['_SCENEPROPINFO']._serialized_end=179
# @@protoc_insertion_point(module_scope)
