# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneEntityGroupInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneEntityInfo_pb2 as SceneEntityInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSceneEntityGroupInfo.proto\x1a\x15SceneEntityInfo.proto\"^\n\x14SceneEntityGroupInfo\x12\r\n\x05state\x18\x0f \x01(\r\x12\x10\n\x08group_id\x18\x08 \x01(\r\x12%\n\x0b\x65ntity_list\x18\x02 \x03(\x0b\x32\x10.SceneEntityInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneEntityGroupInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEENTITYGROUPINFO']._serialized_start=53
  _globals['_SCENEENTITYGROUPINFO']._serialized_end=147
# @@protoc_insertion_point(module_scope)
