# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneEntityTeleportScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EntityMotion_pb2 as EntityMotion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSceneEntityTeleportScRsp.proto\x1a\x12\x45ntityMotion.proto\"m\n\x18SceneEntityTeleportScRsp\x12\x0f\n\x07retcode\x18\x0e \x01(\r\x12\x1a\n\x12\x63lient_pos_version\x18\x0f \x01(\r\x12$\n\rentity_motion\x18\x0b \x01(\x0b\x32\r.EntityMotionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneEntityTeleportScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEENTITYTELEPORTSCRSP']._serialized_start=54
  _globals['_SCENEENTITYTELEPORTSCRSP']._serialized_end=163
# @@protoc_insertion_point(module_scope)
