# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneEntityMoveCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EntityMotion_pb2 as EntityMotion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSceneEntityMoveCsReq.proto\x1a\x12\x45ntityMotion.proto\"S\n\x14SceneEntityMoveCsReq\x12\x10\n\x08\x65ntry_id\x18\t \x01(\r\x12)\n\x12\x65ntity_motion_list\x18\x04 \x03(\x0b\x32\r.EntityMotionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneEntityMoveCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEENTITYMOVECSREQ']._serialized_start=50
  _globals['_SCENEENTITYMOVECSREQ']._serialized_end=133
# @@protoc_insertion_point(module_scope)
