# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneEntityInfo_pb2 as SceneEntityInfo__pb2
import SceneGroupState_pb2 as SceneGroupState__pb2
import SceneEntityGroupInfo_pb2 as SceneEntityGroupInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fSceneInfo.proto\x1a\x15SceneEntityInfo.proto\x1a\x15SceneGroupState.proto\x1a\x1aSceneEntityGroupInfo.proto\"\xbf\x03\n\tSceneInfo\x12\x1a\n\x12\x63lient_pos_version\x18\x0f \x01(\r\x12\x15\n\rgroup_id_list\x18\x0c \x03(\r\x12.\n\nextra_data\x18\xd3\x01 \x03(\x0b\x32\x19.SceneInfo.ExtraDataEntry\x12\x10\n\x08plane_id\x18\x0e \x01(\r\x12\x31\n\x11\x65ntity_group_list\x18\xec\x08 \x03(\x0b\x32\x15.SceneEntityGroupInfo\x12+\n\x10group_state_list\x18\xdd\x04 \x03(\x0b\x32\x10.SceneGroupState\x12\x10\n\x08\x65ntry_id\x18\x02 \x01(\r\x12%\n\x0b\x65ntity_list\x18\n \x03(\x0b\x32\x10.SceneEntityInfo\x12\x10\n\x08\x66loor_id\x18\x08 \x01(\r\x12\x1c\n\x14lighten_section_list\x18\x07 \x03(\r\x12\x18\n\x10leader_entity_id\x18\x05 \x01(\r\x12\x16\n\x0egame_mode_type\x18\r \x01(\r\x12\x10\n\x08world_id\x18\x01 \x01(\r\x1a\x30\n\x0e\x45xtraDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x11:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _SCENEINFO_EXTRADATAENTRY._options = None
  _SCENEINFO_EXTRADATAENTRY._serialized_options = b'8\001'
  _globals['_SCENEINFO']._serialized_start=94
  _globals['_SCENEINFO']._serialized_end=541
  _globals['_SCENEINFO_EXTRADATAENTRY']._serialized_start=493
  _globals['_SCENEINFO_EXTRADATAENTRY']._serialized_end=541
# @@protoc_insertion_point(module_scope)
