# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneCastSkillCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MotionInfo_pb2 as MotionInfo__pb2
import AssistMonsterWave_pb2 as AssistMonsterWave__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19SceneCastSkillCsReq.proto\x1a\x10MotionInfo.proto\x1a\x17\x41ssistMonsterWave.proto\"\xd5\x01\n\x13SceneCastSkillCsReq\x12\x11\n\tcaster_id\x18\r \x01(\r\x12!\n\x19hit_target_entity_id_list\x18\x02 \x03(\r\x12\"\n\rtarget_motion\x18\x06 \x01(\x0b\x32\x0b.MotionInfo\x12\x19\n\x11\x61ttacked_group_id\x18\x0c \x01(\r\x12\x13\n\x0bskill_index\x18\t \x01(\r\x12\x34\n\x18\x61ssist_monster_wave_list\x18\x01 \x03(\x0b\x32\x12.AssistMonsterWaveb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneCastSkillCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENECASTSKILLCSREQ']._serialized_start=73
  _globals['_SCENECASTSKILLCSREQ']._serialized_end=286
# @@protoc_insertion_point(module_scope)
