# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneSummonUnitInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19SceneSummonUnitInfo.proto\"\xaa\x01\n\x13SceneSummonUnitInfo\x12\x16\n\x0e\x63reate_time_ms\x18\x02 \x01(\x04\x12\x19\n\x11trigger_name_list\x18\x0f \x03(\t\x12\x14\n\x0clife_time_ms\x18\x0e \x01(\x11\x12\x18\n\x10\x63\x61ster_entity_id\x18\x06 \x01(\r\x12\x16\n\x0esummon_unit_id\x18\x05 \x01(\r\x12\x18\n\x10\x61ttach_entity_id\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneSummonUnitInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENESUMMONUNITINFO']._serialized_start=30
  _globals['_SCENESUMMONUNITINFO']._serialized_end=200
# @@protoc_insertion_point(module_scope)
