# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneActorInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarType_pb2 as AvatarType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14SceneActorInfo.proto\x1a\x10\x41vatarType.proto\"j\n\x0eSceneActorInfo\x12 \n\x0b\x61vatar_type\x18\n \x01(\x0e\x32\x0b.AvatarType\x12\x16\n\x0e\x62\x61se_avatar_id\x18\x05 \x01(\r\x12\x0b\n\x03uid\x18\x0f \x01(\r\x12\x11\n\tmap_layer\x18\r \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneActorInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEACTORINFO']._serialized_start=42
  _globals['_SCENEACTORINFO']._serialized_end=148
# @@protoc_insertion_point(module_scope)
