# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneCastSkillMpUpdateScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$SceneCastSkillMpUpdateScNotify.proto\"G\n\x1eSceneCastSkillMpUpdateScNotify\x12\x19\n\x11\x61ttacked_group_id\x18\n \x01(\r\x12\n\n\x02mp\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneCastSkillMpUpdateScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENECASTSKILLMPUPDATESCNOTIFY']._serialized_start=40
  _globals['_SCENECASTSKILLMPUPDATESCNOTIFY']._serialized_end=111
# @@protoc_insertion_point(module_scope)
