# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneGroupRefreshType.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSceneGroupRefreshType.proto*\x84\x01\n\x15SceneGroupRefreshType\x12!\n\x1dSCENE_GROUP_REFRESH_TYPE_NONE\x10\x00\x12#\n\x1fSCENE_GROUP_REFRESH_TYPE_LOADED\x10\x01\x12#\n\x1fSCENE_GROUP_REFRESH_TYPE_UNLOAD\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneGroupRefreshType_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEGROUPREFRESHTYPE']._serialized_start=32
  _globals['_SCENEGROUPREFRESHTYPE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
