# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneCastSkill.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14SceneCastSkill.proto*\x81\x01\n\x0eSceneCastSkill\x12\x19\n\x15SCENE_CAST_SKILL_NONE\x10\x00\x12#\n\x1fSCENE_CAST_SKILL_PROJECTILE_HIT\x10\x01\x12/\n+SCENE_CAST_SKILL_PROJECTILE_LIFETIME_FINISH\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneCastSkill_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENECASTSKILL']._serialized_start=25
  _globals['_SCENECASTSKILL']._serialized_end=154
# @@protoc_insertion_point(module_scope)
