# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneGroupRefreshScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneGroupRefreshInfo_pb2 as SceneGroupRefreshInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSceneGroupRefreshScNotify.proto\x1a\x1bSceneGroupRefreshInfo.proto\"O\n\x19SceneGroupRefreshScNotify\x12\x32\n\x12group_refresh_info\x18\x01 \x03(\x0b\x32\x16.SceneGroupRefreshInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneGroupRefreshScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEGROUPREFRESHSCNOTIFY']._serialized_start=64
  _globals['_SCENEGROUPREFRESHSCNOTIFY']._serialized_end=143
# @@protoc_insertion_point(module_scope)
