# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneNpcInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import NpcExtraInfo_pb2 as NpcExtraInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12SceneNpcInfo.proto\x1a\x12NpcExtraInfo.proto\"A\n\x0cSceneNpcInfo\x12!\n\nextra_info\x18\x04 \x01(\x0b\x32\r.NpcExtraInfo\x12\x0e\n\x06npc_id\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneNpcInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENENPCINFO']._serialized_start=42
  _globals['_SCENENPCINFO']._serialized_end=107
# @@protoc_insertion_point(module_scope)
