# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ScenePlaneEventScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dScenePlaneEventScNotify.proto\x1a\x0eItemList.proto\";\n\x17ScenePlaneEventScNotify\x12 \n\rget_item_list\x18\x07 \x01(\x0b\x32\t.ItemListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ScenePlaneEventScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEPLANEEVENTSCNOTIFY']._serialized_start=49
  _globals['_SCENEPLANEEVENTSCNOTIFY']._serialized_end=108
# @@protoc_insertion_point(module_scope)
