# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneBattleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneMonsterWave_pb2 as SceneMonsterWave__pb2
import BattleAvatar_pb2 as BattleAvatar__pb2
import BattleBuff_pb2 as BattleBuff__pb2
import BattleEventBattleInfo_pb2 as BattleEventBattleInfo__pb2
import BattleTargetList_pb2 as BattleTargetList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15SceneBattleInfo.proto\x1a\x16SceneMonsterWave.proto\x1a\x12\x42\x61ttleAvatar.proto\x1a\x10\x42\x61ttleBuff.proto\x1a\x1b\x42\x61ttleEventBattleInfo.proto\x1a\x16\x42\x61ttleTargetList.proto\"\xbf\x03\n\x0fSceneBattleInfo\x12,\n\x11monster_wave_list\x18\x07 \x03(\x0b\x32\x11.SceneMonsterWave\x12\x43\n\x12\x62\x61ttle_target_info\x18\xc7\x04 \x03(\x0b\x32&.SceneBattleInfo.BattleTargetInfoEntry\x12\x11\n\tbattle_id\x18\x0f \x01(\r\x12\x13\n\x0bworld_level\x18\x01 \x01(\r\x12\x1e\n\tbuff_list\x18\x06 \x03(\x0b\x32\x0b.BattleBuff\x12\x14\n\x0crounds_limit\x18\x08 \x01(\r\x12\x19\n\x11logic_random_seed\x18\x03 \x01(\r\x12)\n\x12\x62\x61ttle_avatar_list\x18\x04 \x03(\x0b\x32\r.BattleAvatar\x12\x37\n\x16\x65vent_battle_info_list\x18\x9d\x03 \x03(\x0b\x32\x16.BattleEventBattleInfo\x12\x10\n\x08stage_id\x18\x0b \x01(\r\x1aJ\n\x15\x42\x61ttleTargetInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.BattleTargetList:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneBattleInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _SCENEBATTLEINFO_BATTLETARGETINFOENTRY._options = None
  _SCENEBATTLEINFO_BATTLETARGETINFOENTRY._serialized_options = b'8\001'
  _globals['_SCENEBATTLEINFO']._serialized_start=141
  _globals['_SCENEBATTLEINFO']._serialized_end=588
  _globals['_SCENEBATTLEINFO_BATTLETARGETINFOENTRY']._serialized_start=514
  _globals['_SCENEBATTLEINFO_BATTLETARGETINFOENTRY']._serialized_end=588
# @@protoc_insertion_point(module_scope)
