# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneMonsterWave.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneMonster_pb2 as SceneMonster__pb2
import SceneMonsterWaveParam_pb2 as SceneMonsterWaveParam__pb2
import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SceneMonsterWave.proto\x1a\x12SceneMonster.proto\x1a\x1bSceneMonsterWaveParam.proto\x1a\x0eItemList.proto\"\xa4\x01\n\x10SceneMonsterWave\x12\x0f\n\x07wave_id\x18\x0e \x01(\r\x12\x1c\n\tdrop_list\x18\x04 \x03(\x0b\x32\t.ItemList\x12\x10\n\x08stage_id\x18\x01 \x01(\r\x12#\n\x0cmonster_list\x18\x03 \x03(\x0b\x32\r.SceneMonster\x12*\n\nwave_param\x18\x08 \x01(\x0b\x32\x16.SceneMonsterWaveParamb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneMonsterWave_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEMONSTERWAVE']._serialized_start=92
  _globals['_SCENEMONSTERWAVE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
