# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneGroupRefreshInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneGroupRefreshType_pb2 as SceneGroupRefreshType__pb2
import SceneEntityRefreshInfo_pb2 as SceneEntityRefreshInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSceneGroupRefreshInfo.proto\x1a\x1bSceneGroupRefreshType.proto\x1a\x1cSceneEntityRefreshInfo.proto\"\x9d\x01\n\x15SceneGroupRefreshInfo\x12\r\n\x05state\x18\x07 \x01(\r\x12\x10\n\x08group_id\x18\x06 \x01(\r\x12/\n\x0erefresh_entity\x18\x0f \x03(\x0b\x32\x17.SceneEntityRefreshInfo\x12\x32\n\x12group_refresh_type\x18\x02 \x01(\x0e\x32\x16.SceneGroupRefreshTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneGroupRefreshInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEGROUPREFRESHINFO']._serialized_start=91
  _globals['_SCENEGROUPREFRESHINFO']._serialized_end=248
# @@protoc_insertion_point(module_scope)
