# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SceneEntityInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MotionInfo_pb2 as MotionInfo__pb2
import SceneSummonUnitInfo_pb2 as SceneSummonUnitInfo__pb2
import SceneActorInfo_pb2 as SceneActorInfo__pb2
import SceneNpcMonsterInfo_pb2 as SceneNpcMonsterInfo__pb2
import SceneNpcInfo_pb2 as SceneNpcInfo__pb2
import ScenePropInfo_pb2 as ScenePropInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15SceneEntityInfo.proto\x1a\x10MotionInfo.proto\x1a\x19SceneSummonUnitInfo.proto\x1a\x14SceneActorInfo.proto\x1a\x19SceneNpcMonsterInfo.proto\x1a\x12SceneNpcInfo.proto\x1a\x13ScenePropInfo.proto\"\x94\x02\n\x0fSceneEntityInfo\x12\x11\n\tentity_id\x18\x06 \x01(\r\x12\x10\n\x08group_id\x18\x02 \x01(\r\x12\x1b\n\x06motion\x18\x07 \x01(\x0b\x32\x0b.MotionInfo\x12\x0f\n\x07inst_id\x18\x0f \x01(\r\x12\x1e\n\x05\x61\x63tor\x18\t \x01(\x0b\x32\x0f.SceneActorInfo\x12)\n\x0bnpc_monster\x18\x05 \x01(\x0b\x32\x14.SceneNpcMonsterInfo\x12\x1a\n\x03npc\x18\x0c \x01(\x0b\x32\r.SceneNpcInfo\x12\x1c\n\x04prop\x18\n \x01(\x0b\x32\x0e.ScenePropInfo\x12)\n\x0bsummon_unit\x18\x0e \x01(\x0b\x32\x14.SceneSummonUnitInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SceneEntityInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCENEENTITYINFO']._serialized_start=161
  _globals['_SCENEENTITYINFO']._serialized_end=437
# @@protoc_insertion_point(module_scope)
