# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SelectRogueMiracleScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueMiracleSelectInfo_pb2 as RogueMiracleSelectInfo__pb2
import RogueAchivedMiracleInfo_pb2 as RogueAchivedMiracleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dSelectRogueMiracleScRsp.proto\x1a\x1cRogueMiracleSelectInfo.proto\x1a\x1dRogueAchivedMiracleInfo.proto\"\x96\x01\n\x17SelectRogueMiracleScRsp\x12\x34\n\x12rogue_miracle_info\x18\x0b \x01(\x0b\x32\x18.RogueAchivedMiracleInfo\x12\x34\n\x13miracle_select_info\x18\x08 \x01(\x0b\x32\x17.RogueMiracleSelectInfo\x12\x0f\n\x07retcode\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SelectRogueMiracleScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SELECTROGUEMIRACLESCRSP']._serialized_start=95
  _globals['_SELECTROGUEMIRACLESCRSP']._serialized_end=245
# @@protoc_insertion_point(module_scope)
