# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SelectRogueBuffScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuffSelectInfo_pb2 as RogueBuffSelectInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSelectRogueBuffScRsp.proto\x1a\x19RogueBuffSelectInfo.proto\"\x86\x01\n\x14SelectRogueBuffScRsp\x12\x17\n\x0fmaze_buff_level\x18\x0e \x01(\r\x12.\n\x10\x62uff_select_info\x18\x06 \x01(\x0b\x32\x14.RogueBuffSelectInfo\x12\x14\n\x0cmaze_buff_id\x18\x04 \x01(\r\x12\x0f\n\x07retcode\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SelectRogueBuffScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SELECTROGUEBUFFSCRSP']._serialized_start=58
  _globals['_SELECTROGUEBUFFSCRSP']._serialized_end=192
# @@protoc_insertion_point(module_scope)
