# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SellItemCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemCostList_pb2 as ItemCostList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SellItemCsReq.proto\x1a\x12ItemCostList.proto\"K\n\rSellItemCsReq\x12\x13\n\x0bto_material\x18\x05 \x01(\x08\x12%\n\x0eitem_cost_list\x18\x0f \x01(\x0b\x32\r.ItemCostListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SellItemCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SELLITEMCSREQ']._serialized_start=43
  _globals['_SELLITEMCSREQ']._serialized_end=118
# @@protoc_insertion_point(module_scope)
