# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SendMsgCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatType_pb2 as ChatType__pb2
import MsgType_pb2 as MsgType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12SendMsgCsReq.proto\x1a\x0e\x43hatType.proto\x1a\rMsgType.proto\"z\n\x0cSendMsgCsReq\x12\r\n\x05\x65mote\x18\x0b \x01(\r\x12\x13\n\x0bto_uid_list\x18\x0f \x03(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x1a\n\x08msg_type\x18\x07 \x01(\x0e\x32\x08.MsgType\x12\x1c\n\tchat_type\x18\x0c \x01(\x0e\x32\t.ChatTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SendMsgCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENDMSGCSREQ']._serialized_start=53
  _globals['_SENDMSGCSREQ']._serialized_end=175
# @@protoc_insertion_point(module_scope)
