# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetAssistAvatarCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSetAssistAvatarCsReq.proto\"A\n\x14SetAssistAvatarCsReq\x12\x16\n\x0e\x61vatar_id_list\x18\x0e \x03(\r\x12\x11\n\tavatar_id\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetAssistAvatarCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SETASSISTAVATARCSREQ']._serialized_start=30
  _globals['_SETASSISTAVATARCSREQ']._serialized_end=95
# @@protoc_insertion_point(module_scope)
