# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetDisplayAvatarScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DisplayAvatar_pb2 as DisplayAvatar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSetDisplayAvatarScRsp.proto\x1a\x13\x44isplayAvatar.proto\"U\n\x15SetDisplayAvatarScRsp\x12\x0f\n\x07retcode\x18\r \x01(\r\x12+\n\x13\x64isplay_avatar_list\x18\x0f \x03(\x0b\x32\x0e.DisplayAvatarb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetDisplayAvatarScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SETDISPLAYAVATARSCRSP']._serialized_start=52
  _globals['_SETDISPLAYAVATARSCRSP']._serialized_end=137
# @@protoc_insertion_point(module_scope)
