# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetFriendMarkCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18SetFriendMarkCsReq.proto\"6\n\x12SetFriendMarkCsReq\x12\x13\n\x0bis_set_mark\x18\x06 \x01(\x08\x12\x0b\n\x03uid\x18\x0b \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetFriendMarkCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SETFRIENDMARKCSREQ']._serialized_start=28
  _globals['_SETFRIENDMARKCSREQ']._serialized_end=82
# @@protoc_insertion_point(module_scope)
