# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetGroupCustomSaveDataCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!SetGroupCustomSaveDataCsReq.proto\"Z\n\x1bSetGroupCustomSaveDataCsReq\x12\x17\n\x0fgroup_save_data\x18\x06 \x01(\t\x12\x10\n\x08\x65ntry_id\x18\n \x01(\r\x12\x10\n\x08group_id\x18\x0e \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetGroupCustomSaveDataCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SETGROUPCUSTOMSAVEDATACSREQ']._serialized_start=37
  _globals['_SETGROUPCUSTOMSAVEDATACSREQ']._serialized_end=127
# @@protoc_insertion_point(module_scope)
