# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SetHeroBasicTypeScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HeroBasicType_pb2 as HeroBasicType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bSetHeroBasicTypeScRsp.proto\x1a\x13HeroBasicType.proto\"L\n\x15SetHeroBasicTypeScRsp\x12\"\n\nbasic_type\x18\r \x01(\x0e\x32\x0e.HeroBasicType\x12\x0f\n\x07retcode\x18\x0b \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetHeroBasicTypeScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SETHEROBASICTYPESCRSP']._serialized_start=52
  _globals['_SETHEROBASICTYPESCRSP']._serialized_end=128
# @@protoc_insertion_point(module_scope)
