# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimpleInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendOnlineStatus_pb2 as FriendOnlineStatus__pb2
import AssistSimpleInfo_pb2 as AssistSimpleInfo__pb2
import PlatformType_pb2 as PlatformType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SimpleInfo.proto\x1a\x18\x46riendOnlineStatus.proto\x1a\x16\x41ssistSimpleInfo.proto\x1a\x12PlatformType.proto\"\xa6\x02\n\nSimpleInfo\x12\x18\n\x10last_active_time\x18\x08 \x01(\x03\x12\r\n\x05level\x18\x0b \x01(\r\x12\x16\n\x0e\x63hat_bubble_id\x18\x01 \x01(\r\x12*\n\ronline_status\x18\n \x01(\x0e\x32\x13.FriendOnlineStatus\x12-\n\x12\x61ssist_simple_info\x18\x0f \x03(\x0b\x32\x11.AssistSimpleInfo\x12\x0b\n\x03uid\x18\x05 \x01(\r\x12\x11\n\tis_banned\x18\x06 \x01(\x08\x12\x11\n\thead_icon\x18\x07 \x01(\r\x12$\n\rplatform_type\x18\t \x01(\x0e\x32\r.PlatformType\x12\x11\n\tsignature\x18\x03 \x01(\t\x12\x10\n\x08nickname\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimpleInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SIMPLEINFO']._serialized_start=91
  _globals['_SIMPLEINFO']._serialized_end=385
# @@protoc_insertion_point(module_scope)
