# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StaminaInfoScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19StaminaInfoScNotify.proto\"u\n\x13StaminaInfoScNotify\x12\x0f\n\x07stamina\x18\x01 \x01(\r\x12\x19\n\x11next_recover_time\x18\x0b \x01(\x03\x12\x19\n\x11next_reserve_time\x18\x0f \x01(\x03\x12\x17\n\x0freserve_stamina\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StaminaInfoScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STAMINAINFOSCNOTIFY']._serialized_start=29
  _globals['_STAMINAINFOSCNOTIFY']._serialized_end=146
# @@protoc_insertion_point(module_scope)
