# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartNewChallengeStoryBuffInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$StartNewChallengeStoryBuffInfo.proto\"I\n\x1eStartNewChallengeStoryBuffInfo\x12\x13\n\x0bsecond_half\x18\x02 \x01(\r\x12\x12\n\nfirst_half\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartNewChallengeStoryBuffInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTNEWCHALLENGESTORYBUFFINFO']._serialized_start=40
  _globals['_STARTNEWCHALLENGESTORYBUFFINFO']._serialized_end=113
# @@protoc_insertion_point(module_scope)
