# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartChallengeStoryBuffInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!StartChallengeStoryBuffInfo.proto\"M\n\x1bStartChallengeStoryBuffInfo\x12\x16\n\x0estory_buff_one\x18\x07 \x01(\r\x12\x16\n\x0estory_buff_two\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartChallengeStoryBuffInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTCHALLENGESTORYBUFFINFO']._serialized_start=37
  _globals['_STARTCHALLENGESTORYBUFFINFO']._serialized_end=114
# @@protoc_insertion_point(module_scope)
