# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartChallengeScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChallengeInfo_pb2 as ChallengeInfo__pb2
import LineupInfo_pb2 as LineupInfo__pb2
import SceneInfo_pb2 as SceneInfo__pb2
import ChallengeExtInfo_pb2 as ChallengeExtInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19StartChallengeScRsp.proto\x1a\x13\x43hallengeInfo.proto\x1a\x10LineupInfo.proto\x1a\x0fSceneInfo.proto\x1a\x16\x43hallengeExtInfo.proto\"\xb0\x01\n\x13StartChallengeScRsp\x12 \n\x0blineup_list\x18\x05 \x03(\x0b\x32\x0b.LineupInfo\x12#\n\x08\x65xt_info\x18\x08 \x01(\x0b\x32\x11.ChallengeExtInfo\x12\x19\n\x05scene\x18\n \x01(\x0b\x32\n.SceneInfo\x12&\n\x0e\x63hallenge_info\x18\x0b \x01(\x0b\x32\x0e.ChallengeInfo\x12\x0f\n\x07retcode\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartChallengeScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTCHALLENGESCRSP']._serialized_start=110
  _globals['_STARTCHALLENGESCRSP']._serialized_end=286
# @@protoc_insertion_point(module_scope)
