# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartChallengeCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import StartChallengeStoryInfo_pb2 as StartChallengeStoryInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19StartChallengeCsReq.proto\x1a\x1dStartChallengeStoryInfo.proto\"{\n\x13StartChallengeCsReq\x12\x0f\n\x07lineup2\x18\x0e \x03(\r\x12\x14\n\x0c\x63hallenge_id\x18\x0f \x01(\r\x12,\n\nstory_info\x18\x03 \x01(\x0b\x32\x18.StartChallengeStoryInfo\x12\x0f\n\x07lineup1\x18\x07 \x03(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartChallengeCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTCHALLENGECSREQ']._serialized_start=60
  _globals['_STARTCHALLENGECSREQ']._serialized_end=183
# @@protoc_insertion_point(module_scope)
