# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartChallengeStoryInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import StartChallengeStoryBuffInfo_pb2 as StartChallengeStoryBuffInfo__pb2
import StartNewChallengeStoryBuffInfo_pb2 as StartNewChallengeStoryBuffInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dStartChallengeStoryInfo.proto\x1a!StartChallengeStoryBuffInfo.proto\x1a$StartNewChallengeStoryBuffInfo.proto\"\x9f\x01\n\x17StartChallengeStoryInfo\x12\x37\n\x0fstory_buff_info\x18\x0f \x01(\x0b\x32\x1c.StartChallengeStoryBuffInfoH\x00\x12>\n\x13new_story_buff_info\x18\x0e \x01(\x0b\x32\x1f.StartNewChallengeStoryBuffInfoH\x00\x42\x0b\n\tbuff_infob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartChallengeStoryInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTCHALLENGESTORYINFO']._serialized_start=107
  _globals['_STARTCHALLENGESTORYINFO']._serialized_end=266
# @@protoc_insertion_point(module_scope)
