# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartCocoonStageScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SceneBattleInfo_pb2 as SceneBattleInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bStartCocoonStageScRsp.proto\x1a\x15SceneBattleInfo.proto\"\x88\x01\n\x15StartCocoonStageScRsp\x12\x16\n\x0eprop_entity_id\x18\x0c \x01(\r\x12%\n\x0b\x62\x61ttle_info\x18\x03 \x01(\x0b\x32\x10.SceneBattleInfo\x12\x11\n\tcocoon_id\x18\t \x01(\r\x12\x0f\n\x07retcode\x18\x07 \x01(\r\x12\x0c\n\x04wave\x18\x0f \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartCocoonStageScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTCOCOONSTAGESCRSP']._serialized_start=55
  _globals['_STARTCOCOONSTAGESCRSP']._serialized_end=191
# @@protoc_insertion_point(module_scope)
