# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartPartialChallengeScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import LineupInfo_pb2 as LineupInfo__pb2
import ChallengeInfo_pb2 as ChallengeInfo__pb2
import SceneInfo_pb2 as SceneInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n StartPartialChallengeScRsp.proto\x1a\x10LineupInfo.proto\x1a\x13\x43hallengeInfo.proto\x1a\x0fSceneInfo.proto\"\x8d\x01\n\x1aStartPartialChallengeScRsp\x12\x1b\n\x06lineup\x18\t \x01(\x0b\x32\x0b.LineupInfo\x12&\n\x0e\x63hallenge_info\x18\x0c \x01(\x0b\x32\x0e.ChallengeInfo\x12\x19\n\x05scene\x18\x07 \x01(\x0b\x32\n.SceneInfo\x12\x0f\n\x07retcode\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartPartialChallengeScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTPARTIALCHALLENGESCRSP']._serialized_start=93
  _globals['_STARTPARTIALCHALLENGESCRSP']._serialized_end=234
# @@protoc_insertion_point(module_scope)
