# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartCocoonStageCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bStartCocoonStageCsReq.proto\"e\n\x15StartCocoonStageCsReq\x12\x11\n\tcocoon_id\x18\t \x01(\r\x12\x13\n\x0bworld_level\x18\x0f \x01(\r\x12\x0c\n\x04wave\x18\x02 \x01(\r\x12\x16\n\x0eprop_entity_id\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartCocoonStageCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTCOCOONSTAGECSREQ']._serialized_start=31
  _globals['_STARTCOCOONSTAGECSREQ']._serialized_end=132
# @@protoc_insertion_point(module_scope)
