# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartRogueCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15StartRogueCsReq.proto\"U\n\x0fStartRogueCsReq\x12\x1b\n\x13\x62\x61se_avatar_id_list\x18\r \x03(\r\x12\x0f\n\x07\x61rea_id\x18\x07 \x01(\r\x12\x14\n\x0c\x62uff_aeon_id\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartRogueCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTROGUECSREQ']._serialized_start=25
  _globals['_STARTROGUECSREQ']._serialized_end=110
# @@protoc_insertion_point(module_scope)
