# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StartPartialChallengeCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n StartPartialChallengeCsReq.proto\"Z\n\x1aStartPartialChallengeCsReq\x12\x14\n\x0c\x63hallenge_id\x18\x06 \x01(\r\x12\x0f\n\x07\x62uff_id\x18\x0f \x01(\r\x12\x15\n\ris_first_half\x18\x0c \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StartPartialChallengeCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTPARTIALCHALLENGECSREQ']._serialized_start=36
  _globals['_STARTPARTIALCHALLENGECSREQ']._serialized_end=126
# @@protoc_insertion_point(module_scope)
