# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncRogueBuffSelectInfoScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueBuffSelectInfo_pb2 as RogueBuffSelectInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%SyncRogueBuffSelectInfoScNotify.proto\x1a\x19RogueBuffSelectInfo.proto\"Q\n\x1fSyncRogueBuffSelectInfoScNotify\x12.\n\x10\x62uff_select_info\x18\x05 \x01(\x0b\x32\x14.RogueBuffSelectInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncRogueBuffSelectInfoScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCROGUEBUFFSELECTINFOSCNOTIFY']._serialized_start=68
  _globals['_SYNCROGUEBUFFSELECTINFOSCNOTIFY']._serialized_end=149
# @@protoc_insertion_point(module_scope)
