# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncApplyFriendScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendApplyInfo_pb2 as FriendApplyInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dSyncApplyFriendScNotify.proto\x1a\x15\x46riendApplyInfo.proto\"F\n\x17SyncApplyFriendScNotify\x12+\n\x11\x66riend_apply_info\x18\x04 \x01(\x0b\x32\x10.FriendApplyInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncApplyFriendScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCAPPLYFRIENDSCNOTIFY']._serialized_start=56
  _globals['_SYNCAPPLYFRIENDSCNOTIFY']._serialized_end=126
# @@protoc_insertion_point(module_scope)
