# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncRogueVirtualItemInfoScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueVirtualItemInfo_pb2 as RogueVirtualItemInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&SyncRogueVirtualItemInfoScNotify.proto\x1a\x1aRogueVirtualItemInfo.proto\"Z\n SyncRogueVirtualItemInfoScNotify\x12\x36\n\x17rogue_virtual_item_info\x18\r \x01(\x0b\x32\x15.RogueVirtualItemInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncRogueVirtualItemInfoScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCROGUEVIRTUALITEMINFOSCNOTIFY']._serialized_start=70
  _globals['_SYNCROGUEVIRTUALITEMINFOSCNOTIFY']._serialized_end=160
# @@protoc_insertion_point(module_scope)
