# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncRogueMiracleSelectInfoScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueMiracleSelectInfo_pb2 as RogueMiracleSelectInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(SyncRogueMiracleSelectInfoScNotify.proto\x1a\x1cRogueMiracleSelectInfo.proto\"Z\n\"SyncRogueMiracleSelectInfoScNotify\x12\x34\n\x13miracle_select_info\x18\x07 \x01(\x0b\x32\x17.RogueMiracleSelectInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncRogueMiracleSelectInfoScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCROGUEMIRACLESELECTINFOSCNOTIFY']._serialized_start=74
  _globals['_SYNCROGUEMIRACLESELECTINFOSCNOTIFY']._serialized_end=164
# @@protoc_insertion_point(module_scope)
