# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncReason.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SyncReason.proto*\x94\x01\n\nSyncReason\x12\x14\n\x10SYNC_REASON_NONE\x10\x00\x12\x16\n\x12SYNC_REASON_MP_ADD\x10\x01\x12\x1f\n\x1bSYNC_REASON_MP_ADD_PROP_HIT\x10\x02\x12\x16\n\x12SYNC_REASON_HP_ADD\x10\x03\x12\x1f\n\x1bSYNC_REASON_HP_ADD_PROP_HIT\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncReason_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCREASON']._serialized_start=21
  _globals['_SYNCREASON']._serialized_end=169
# @@protoc_insertion_point(module_scope)
