# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncRogueCommonActionResultScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueActionResult_pb2 as RogueActionResult__pb2
import RogueCommonActionResultDisplayType_pb2 as RogueCommonActionResultDisplayType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)SyncRogueCommonActionResultScNotify.proto\x1a\x17RogueActionResult.proto\x1a(RogueCommonActionResultDisplayType.proto\"\xaa\x01\n#SyncRogueCommonActionResultScNotify\x12\x18\n\x10rogue_version_id\x18\n \x01(\r\x12.\n\x12\x61\x63tion_result_list\x18\x02 \x03(\x0b\x32\x12.RogueActionResult\x12\x39\n\x0c\x64isplay_type\x18\t \x01(\x0e\x32#.RogueCommonActionResultDisplayTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncRogueCommonActionResultScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCROGUECOMMONACTIONRESULTSCNOTIFY']._serialized_start=113
  _globals['_SYNCROGUECOMMONACTIONRESULTSCNOTIFY']._serialized_end=283
# @@protoc_insertion_point(module_scope)
