# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncEntityBuffChangeListScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EntityBuffChangeInfo_pb2 as EntityBuffChangeInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&SyncEntityBuffChangeListScNotify.proto\x1a\x1a\x45ntityBuffChangeInfo.proto\"X\n SyncEntityBuffChangeListScNotify\x12\x34\n\x15\x65ntity_buff_info_list\x18\x08 \x03(\x0b\x32\x15.EntityBuffChangeInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncEntityBuffChangeListScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCENTITYBUFFCHANGELISTSCNOTIFY']._serialized_start=70
  _globals['_SYNCENTITYBUFFCHANGELISTSCNOTIFY']._serialized_end=158
# @@protoc_insertion_point(module_scope)
