# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncRogueCommonPendingActionScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueCommonPendingAction_pb2 as RogueCommonPendingAction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*SyncRogueCommonPendingActionScNotify.proto\x1a\x1eRogueCommonPendingAction.proto\"\x80\x01\n$SyncRogueCommonPendingActionScNotify\x12>\n\x1brogue_common_pending_action\x18\r \x01(\x0b\x32\x19.RogueCommonPendingAction\x12\x18\n\x10rogue_version_id\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncRogueCommonPendingActionScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCROGUECOMMONPENDINGACTIONSCNOTIFY']._serialized_start=79
  _globals['_SYNCROGUECOMMONPENDINGACTIONSCNOTIFY']._serialized_end=207
# @@protoc_insertion_point(module_scope)
