# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncLineupNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SyncReason_pb2 as SyncReason__pb2
import LineupInfo_pb2 as LineupInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SyncLineupNotify.proto\x1a\x10SyncReason.proto\x1a\x10LineupInfo.proto\"Q\n\x10SyncLineupNotify\x12 \n\x0breason_list\x18\x04 \x03(\x0e\x32\x0b.SyncReason\x12\x1b\n\x06lineup\x18\t \x01(\x0b\x32\x0b.LineupInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncLineupNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCLINEUPNOTIFY']._serialized_start=62
  _globals['_SYNCLINEUPNOTIFY']._serialized_end=143
# @@protoc_insertion_point(module_scope)
