# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncRogueDialogueEventDataScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueDialogueEvent_pb2 as RogueDialogueEvent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(SyncRogueDialogueEventDataScNotify.proto\x1a\x18RogueDialogueEvent.proto\"W\n\"SyncRogueDialogueEventDataScNotify\x12\x31\n\x14rogue_dialogue_event\x18\r \x03(\x0b\x32\x13.RogueDialogueEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncRogueDialogueEventDataScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCROGUEDIALOGUEEVENTDATASCNOTIFY']._serialized_start=70
  _globals['_SYNCROGUEDIALOGUEEVENTDATASCNOTIFY']._serialized_end=157
# @@protoc_insertion_point(module_scope)
