# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncHandleFriendScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendListInfo_pb2 as FriendListInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSyncHandleFriendScNotify.proto\x1a\x14\x46riendListInfo.proto\"k\n\x18SyncHandleFriendScNotify\x12\x0b\n\x03uid\x18\n \x01(\r\x12+\n\x12handle_friend_info\x18\x01 \x01(\x0b\x32\x0f.FriendListInfo\x12\x15\n\rhandle_result\x18\x06 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncHandleFriendScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCHANDLEFRIENDSCNOTIFY']._serialized_start=56
  _globals['_SYNCHANDLEFRIENDSCNOTIFY']._serialized_end=163
# @@protoc_insertion_point(module_scope)
