# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncRogueMapRoomScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueRoom_pb2 as RogueRoom__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eSyncRogueMapRoomScNotify.proto\x1a\x0fRogueRoom.proto\"H\n\x18SyncRogueMapRoomScNotify\x12\x1c\n\x08\x63ur_room\x18\r \x01(\x0b\x32\n.RogueRoom\x12\x0e\n\x06map_id\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncRogueMapRoomScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCROGUEMAPROOMSCNOTIFY']._serialized_start=51
  _globals['_SYNCROGUEMAPROOMSCNOTIFY']._serialized_end=123
# @@protoc_insertion_point(module_scope)
