# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncRogueFinishScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueFinishInfo_pb2 as RogueFinishInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dSyncRogueFinishScNotify.proto\x1a\x15RogueFinishInfo.proto\"@\n\x17SyncRogueFinishScNotify\x12%\n\x0b\x66inish_info\x18\n \x01(\x0b\x32\x10.RogueFinishInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncRogueFinishScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCROGUEFINISHSCNOTIFY']._serialized_start=56
  _globals['_SYNCROGUEFINISHSCNOTIFY']._serialized_end=120
# @@protoc_insertion_point(module_scope)
