# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SyncRogueStatusScNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RogueStatus_pb2 as RogueStatus__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dSyncRogueStatusScNotify.proto\x1a\x11RogueStatus.proto\"=\n\x17SyncRogueStatusScNotify\x12\"\n\x0crogue_status\x18\x0f \x01(\x0e\x32\x0c.RogueStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SyncRogueStatusScNotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCROGUESTATUSSCNOTIFY']._serialized_start=52
  _globals['_SYNCROGUESTATUSSCNOTIFY']._serialized_end=113
# @@protoc_insertion_point(module_scope)
