# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeMailAttachmentCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dTakeMailAttachmentCsReq.proto\"K\n\x17TakeMailAttachmentCsReq\x12\x14\n\x0cmail_id_list\x18\x01 \x03(\r\x12\x1a\n\x12optional_reward_id\x18\x07 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TakeMailAttachmentCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TAKEMAILATTACHMENTCSREQ']._serialized_start=33
  _globals['_TAKEMAILATTACHMENTCSREQ']._serialized_end=108
# @@protoc_insertion_point(module_scope)
