# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakenChallengeRewardInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eTakenChallengeRewardInfo.proto\x1a\x0eItemList.proto\"I\n\x18TakenChallengeRewardInfo\x12\x19\n\x06reward\x18\x03 \x01(\x0b\x32\t.ItemList\x12\x12\n\nstar_count\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TakenChallengeRewardInfo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TAKENCHALLENGEREWARDINFO']._serialized_start=50
  _globals['_TAKENCHALLENGEREWARDINFO']._serialized_end=123
# @@protoc_insertion_point(module_scope)
