# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeMailAttachmentScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dTakeMailAttachmentScRsp.proto\x1a\x0eItemList.proto\"d\n\x17TakeMailAttachmentScRsp\x12\x19\n\x11succ_mail_id_list\x18\x0b \x03(\r\x12\x1d\n\nattachment\x18\x04 \x01(\x0b\x32\t.ItemList\x12\x0f\n\x07retcode\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TakeMailAttachmentScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TAKEMAILATTACHMENTSCRSP']._serialized_start=49
  _globals['_TAKEMAILATTACHMENTSCRSP']._serialized_end=149
# @@protoc_insertion_point(module_scope)
