# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakeOffRelicCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17TakeOffRelicCsReq.proto\"?\n\x11TakeOffRelicCsReq\x12\x11\n\tslot_list\x18\x08 \x03(\r\x12\x17\n\x0f\x65quip_avatar_id\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TakeOffRelicCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TAKEOFFRELICCSREQ']._serialized_start=27
  _globals['_TAKEOFFRELICCSREQ']._serialized_end=90
# @@protoc_insertion_point(module_scope)
