# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TakePromotionRewardScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eTakePromotionRewardScRsp.proto\x1a\x0eItemList.proto\"K\n\x18TakePromotionRewardScRsp\x12\x1e\n\x0breward_list\x18\r \x01(\x0b\x32\t.ItemList\x12\x0f\n\x07retcode\x18\x06 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TakePromotionRewardScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TAKEPROMOTIONREWARDSCRSP']._serialized_start=50
  _globals['_TAKEPROMOTIONREWARDSCRSP']._serialized_end=125
# @@protoc_insertion_point(module_scope)
