# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnlockHeroBasicTypeCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HeroBasicType_pb2 as HeroBasicType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eUnlockHeroBasicTypeCsReq.proto\x1a\x13HeroBasicType.proto\">\n\x18UnlockHeroBasicTypeCsReq\x12\"\n\nbasic_type\x18\n \x01(\x0e\x32\x0e.HeroBasicTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UnlockHeroBasicTypeCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UNLOCKHEROBASICTYPECSREQ']._serialized_start=55
  _globals['_UNLOCKHEROBASICTYPECSREQ']._serialized_end=117
# @@protoc_insertion_point(module_scope)
