# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UnlockHeroBasicTypeScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import HeroBasicType_pb2 as HeroBasicType__pb2
import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eUnlockHeroBasicTypeScRsp.proto\x1a\x13HeroBasicType.proto\x1a\x0eItemList.proto\"\x88\x01\n\x18UnlockHeroBasicTypeScRsp\x12\x1c\n\x14unlocked_basic_types\x18\x0c \x03(\r\x12\x0f\n\x07retcode\x18\x03 \x01(\r\x12\"\n\nbasic_type\x18\x08 \x01(\x0e\x32\x0e.HeroBasicType\x12\x19\n\x06reward\x18\x01 \x01(\x0b\x32\t.ItemListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UnlockHeroBasicTypeScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UNLOCKHEROBASICTYPESCRSP']._serialized_start=72
  _globals['_UNLOCKHEROBASICTYPESCRSP']._serialized_end=208
# @@protoc_insertion_point(module_scope)
