# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UseItemScRsp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ItemList_pb2 as ItemList__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12UseItemScRsp.proto\x1a\x0eItemList.proto\"l\n\x0cUseItemScRsp\x12\x13\n\x0buse_item_id\x18\x06 \x01(\r\x12\x1e\n\x0breturn_data\x18\x04 \x01(\x0b\x32\t.ItemList\x12\x16\n\x0euse_item_count\x18\r \x01(\r\x12\x0f\n\x07retcode\x18\t \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UseItemScRsp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USEITEMSCRSP']._serialized_start=38
  _globals['_USEITEMSCRSP']._serialized_end=146
# @@protoc_insertion_point(module_scope)
