# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UseItemCsReq.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AvatarType_pb2 as AvatarType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12UseItemCsReq.proto\x1a\x10\x41vatarType.proto\"\x95\x01\n\x0cUseItemCsReq\x12\x1a\n\x12optional_reward_id\x18\x04 \x01(\r\x12\x13\n\x0buse_item_id\x18\x07 \x01(\r\x12\x16\n\x0e\x62\x61se_avatar_id\x18\n \x01(\r\x12\x16\n\x0euse_item_count\x18\r \x01(\r\x12$\n\x0fuse_avatar_type\x18\x08 \x01(\x0e\x32\x0b.AvatarTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UseItemCsReq_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USEITEMCSREQ']._serialized_start=41
  _globals['_USEITEMCSREQ']._serialized_end=190
# @@protoc_insertion_point(module_scope)
